This is the dataset from Kaggle Dataset 

In [1]:
import pandas as pd

establishment_df=pd.read_csv("data/Grab SG Restaurants.csv")

establishment_df.head()


id_source             name                     address    country  \
0         SGDD01085    Texas Chicken    Texas Chicken - VivoCity  Singapore   
1  4-CYTDLPUJEP53N6           Subway           Subway - Vivocity  Singapore   
2         SGDD05605         LiHO Tea        LiHO Tea - Vivo City  Singapore   
3         SGDD07548         Wingstop         Wingstop - VivoCity  Singapore   
4  4-CY2ZLZLTT2EDJ2  Le Shrimp Ramen  Le Shrimp Ramen - Vivocity  Singapore   

                                             cuisine currency  delivery_cost  \
0  ["Western", "Fast Food", "Halal", "Chicken", "...      SGD          570.0   
1  ["Healthy", "Sandwiches", "Fast Food", "Halal"...      SGD          570.0   
2  ["Same Prices In-Store", "Beverages", "Local",...      SGD          560.0   
3  ["Halal", "Chicken", "Fast Food", "Burger", "W...      SGD          560.0   
4          ["Japanese", "Ramen", "Noodles", "Asian"]      SGD          570.0   

        lat         lon                                      opening_hours  \
0  1.264792  103.822103  {"open": true, "displayedHours": "10:30-21:30"...   
1  1.264741  103.822072  {"open": true, "displayedHours": "12:00-19:00"...   
2  1.264309  103.821369  {"open": true, "displayedHours": "11:30-20:45"...   
3  1.263527  103.821712  {"open": true, "displayedHours": "11:00-21:00"...   
4  1.264810  103.822554  {"open": true, "displayedHours": "10:30-21:00"...   

                                           image_url  radius  rating  \
0  https://d1sag4ddilekf6.cloudfront.net/compress...    5000     3.8   
1  https://d1sag4ddilekf6.cloudfront.net/compress...    3000     4.2   
2  https://d1sag4ddilekf6.cloudfront.net/compress...    5000     4.5   
3  https://d1sag4ddilekf6.cloudfront.net/compress...    5000     4.4   
4  https://d1sag4ddilekf6.cloudfront.net/compress...    5000     4.6   

   reviews_nr   delivery_options  \
0      1591.0      ONLY_DELIVERY   
1       197.0      ONLY_DELIVERY   
2       353.0  DELIVERY_TAKEAWAY   
3      1391.0      ONLY_DELIVERY   
4       309.0  DELIVERY_TAKEAWAY   

                                               promo loc_type delivery_by  \
0  Use 'TEATIME' for FREE delivery between 3PM to...     FOOD        GRAB   
1  Use 'TEATIME' for FREE delivery between 3PM to...     FOOD        GRAB   
2  Use 'TEATIME' for FREE delivery between 3PM to...     FOOD        GRAB   
3  Use 'TEATIME' for FREE delivery between 3PM to...     FOOD        GRAB   
4  Use 'TEATIME' for FREE delivery between 3PM to...     FOOD        GRAB   

   delivery_time  
0           43.0  
1           42.0  
2           41.0  
3           45.0  
4           44.0

## Exploratory Data Analysis

Simple exploratory Data Analysis to understand the data

In [2]:
establishment_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16136 entries, 0 to 16135
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   id_source         16136 non-null  object 
 1   name              16130 non-null  object 
 2   address           16136 non-null  object 
 3   country           16136 non-null  object 
 4   cuisine           16134 non-null  object 
 5   currency          16117 non-null  object 
 6   delivery_cost     16085 non-null  float64
 7   lat               16136 non-null  float64
 8   lon               16136 non-null  float64
 9   opening_hours     16136 non-null  object 
 10  image_url         16125 non-null  object 
 11  radius            16136 non-null  int64  
 12  rating            14004 non-null  float64
 13  reviews_nr        13602 non-null  float64
 14  delivery_options  16136 non-null  object 
 15  promo             8777 non-null   object 
 16  loc_type          16136 non-null  object

So the dataset of 16136 rows of grab restaurants
you can see from the count that there are empty values for each column

In [3]:
establishment_df.describe()

delivery_cost           lat           lon        radius        rating  \
count   16085.000000  16136.000000  16136.000000  16136.000000  14004.000000   
mean      984.926640      1.338491    103.843448   6871.493183      4.238346   
std       656.544752      0.045269      0.062123   6170.013565      0.619217   
min       199.000000      1.230454    103.625677    578.000000     -1.000000   
25%       450.000000      1.304839    103.806196   4999.000000      4.000000   
50%       680.000000      1.332154    103.846004   5000.000000      4.300000   
75%      1610.000000      1.362576    103.885674   5000.000000      4.600000   
max     14000.000000      1.469011    103.997253  25000.000000      5.000000   

         reviews_nr  delivery_time  
count  13602.000000   15953.000000  
mean     343.591604      37.552811  
std      846.893054      15.728705  
min        1.000000      15.000000  
25%       16.000000      28.000000  
50%       74.000000      34.000000  
75%      303.000000      42.000000  
max    21113.000000     169.000000

# Data Cleaning on 'address' column: SAILA
### Which involves data inspection, Data correction, Data standardization and Data transformation.

- Remove duplicates-> the address column values are keyed in together with the establishment name seperated by "-"
- Standardize the wording -> currently the values entries are inconsistent cases: 
    example : 'Vivocity' , 'VivoCity'
- Inconsistent entry -> for the same address it was entered inconsistantly
    example: 'Vivocity', 'Vivo City' , 'Vivocity Shopping mall'
- Need to filter and transform the address entries to avoid unnecessary disticnt values.

In [4]:
#Splitting the data .Removing values before '-'
establishment_df['address'] = establishment_df['address'].apply(lambda x: x.split('-')[-1].strip())

# Display the modified DataFrame
print(establishment_df)


              id_source                         name  \
0             SGDD01085                Texas Chicken   
1      4-CYTDLPUJEP53N6                       Subway   
2             SGDD05605                     LiHO Tea   
3             SGDD07548                     Wingstop   
4      4-CY2ZLZLTT2EDJ2              Le Shrimp Ramen   
...                 ...                          ...   
16131  4-CZNFTYKKVA3UN2                 Minjiangkueh   
16132         SGDD01192  The Modern Izakaya by Tatsu   
16133         SGDD00961               Raj Restaurant   
16134  4-C2AHJVATN7C2RE   Albismi Indian Muslim Food   
16135  4-C2DXFEK2R6KJTJ  Zam Zam Indian Special Food   

                        address    country  \
0                      VivoCity  Singapore   
1                      Vivocity  Singapore   
2                     Vivo City  Singapore   
3                      VivoCity  Singapore   
4                      Vivocity  Singapore   
...                         ...        ...   
16131

#### To Understand the dataframe entries-Distinct values at address column

In [5]:

distinct_addresses = establishment_df['address'].unique()
address_counts = establishment_df['address'].value_counts()

# Display distinct values and their counts
print("Distinct Addresses:")
print(distinct_addresses)
print("\nCount of Distinct Addresses:")
print(address_counts.head(50))


Distinct Addresses:
['VivoCity' 'Vivocity' 'Vivo City' ... 'Wilmer Place' '18)'
 'SOHO @ Farrer']

Count of Distinct Addresses:
address
Northpoint City                 90
Jurong Point                    86
Waterway Point                  81
Causeway Point                  76
Plaza Singapura                 74
Changi City Point               74
Westgate                        70
Geylang Road                    70
Suntec City Mall                65
East Coast Road                 62
Tiong Bahru Plaza               60
Great World City                59
Compass One                     59
Vivocity                        58
Hillion Mall                    57
NEX                             57
Our Tampines Hub                55
JEM                             55
Bedok Mall                      53
Tampines Mall                   49
New Upper Changi Road           48
Century Square                  45
Jewel Changi Airport            45
Harbourfront Centre             45
Vivo City               

#### Total Distinct values count

In [6]:
# Assuming 'establishment_df' is your DataFrame containing the data
total_distinct_addresses = establishment_df['address'].nunique()

# Display the total number of distinct addresses
print("Total distinct addresses:", total_distinct_addresses)


Total distinct addresses: 4998


### Standardize all the add with tittle case.

In [7]:
# Assuming 'establishment_df' is your DataFrame containing the data
establishment_df['address'] = establishment_df['address'].apply(lambda x: x.title())

# Display the modified DataFrame
establishment_df.head()


id_source             name    address    country  \
0         SGDD01085    Texas Chicken   Vivocity  Singapore   
1  4-CYTDLPUJEP53N6           Subway   Vivocity  Singapore   
2         SGDD05605         LiHO Tea  Vivo City  Singapore   
3         SGDD07548         Wingstop   Vivocity  Singapore   
4  4-CY2ZLZLTT2EDJ2  Le Shrimp Ramen   Vivocity  Singapore   

                                             cuisine currency  delivery_cost  \
0  ["Western", "Fast Food", "Halal", "Chicken", "...      SGD          570.0   
1  ["Healthy", "Sandwiches", "Fast Food", "Halal"...      SGD          570.0   
2  ["Same Prices In-Store", "Beverages", "Local",...      SGD          560.0   
3  ["Halal", "Chicken", "Fast Food", "Burger", "W...      SGD          560.0   
4          ["Japanese", "Ramen", "Noodles", "Asian"]      SGD          570.0   

        lat         lon                                      opening_hours  \
0  1.264792  103.822103  {"open": true, "displayedHours": "10:30-21:30"...   
1  1.264741  103.822072  {"open": true, "displayedHours": "12:00-19:00"...   
2  1.264309  103.821369  {"open": true, "displayedHours": "11:30-20:45"...   
3  1.263527  103.821712  {"open": true, "displayedHours": "11:00-21:00"...   
4  1.264810  103.822554  {"open": true, "displayedHours": "10:30-21:00"...   

                                           image_url  radius  rating  \
0  https://d1sag4ddilekf6.cloudfront.net/compress...    5000     3.8   
1  https://d1sag4ddilekf6.cloudfront.net/compress...    3000     4.2   
2  https://d1sag4ddilekf6.cloudfront.net/compress...    5000     4.5   
3  https://d1sag4ddilekf6.cloudfront.net/compress...    5000     4.4   
4  https://d1sag4ddilekf6.cloudfront.net/compress...    5000     4.6   

   reviews_nr   delivery_options  \
0      1591.0      ONLY_DELIVERY   
1       197.0      ONLY_DELIVERY   
2       353.0  DELIVERY_TAKEAWAY   
3      1391.0      ONLY_DELIVERY   
4       309.0  DELIVERY_TAKEAWAY   

                                               promo loc_type delivery_by  \
0  Use 'TEATIME' for FREE delivery between 3PM to...     FOOD        GRAB   
1  Use 'TEATIME' for FREE delivery between 3PM to...     FOOD        GRAB   
2  Use 'TEATIME' for FREE delivery between 3PM to...     FOOD        GRAB   
3  Use 'TEATIME' for FREE delivery between 3PM to...     FOOD        GRAB   
4  Use 'TEATIME' for FREE delivery between 3PM to...     FOOD        GRAB   

   delivery_time  
0           43.0  
1           42.0  
2           41.0  
3           45.0  
4           44.0

#### Cleaning the [address] column further by changing the case to tittle form.The distinct count reduced from 4998 to 4883

In [8]:
#To find the total distinct value after changing the values in address column to tittle case.
total_distinct_addresses = establishment_df['address'].nunique()

# Display the total number of distinct addresses
print("Total distinct addresses:", total_distinct_addresses)

Total distinct addresses: 4883


### Filtering out the distinct data using alphabets to verify the values in the column and to do necessary transformation needed if the data was not input in accurately.

In [9]:
# Assuming 'establishment_df' is your DataFrame containing the data

# Step 1: Filter the DataFrame
filtered_df = establishment_df[establishment_df['address'].str.lower().str.startswith(('a'))]

# Step 2: Extract distinct values from the filtered DataFrame
distinct_addresses_filtered = filtered_df['address'].unique()

# Step 3: Sort the distinct values alphabetically
distinct_addresses_filtered_sorted = sorted(distinct_addresses_filtered)

# Display the sorted distinct values
print("Distinct addresses starting with 'a':")
for address in distinct_addresses_filtered_sorted:
    print(address)


Distinct addresses starting with 'a':
A' Posh Bizhub
A'Posh Bizhub
Abc Brickworks Food Centre
Abc Brickworks Market & Food Centre
Abc Brickworks Market & Food Centre [Stall 113]
Abc Brickworks Market & Food Centre [Stall 120]
Abc Brickworks Market & Food Centre [Stall 12]
Abc Brickworks Market & Food Centre [Stall 143]
Abc Brickworks Market & Food Centre [Stall 15]
Abc Brickworks Market & Food Centre [Stall 18]
Abc Brickworks Market And Food Centre [Stall 10]
Abc Brickworks Market And Food Centre [Stall 2]
Abc Brickworks Market And Food Centre [Stall 8]
Acacia Breeze @ Yishun
Acacia Court
Academia
Academy Of Singapore Teachers
Ace Community Club
Adam Road Food Centre
Adda
Adelphi Park Estate
Admiralty
Admiralty Link
Admiralty Street
Admiralty [Islandwide Delivery]
Admiralty[Islandwide Delivery]
Admirax
Admirax [Islandwide Delivery]
Agape Village
Ah Hood
Ah Hood Road
Ah Wang Kway Chap
Air View Building
Airport Boulevard
Airport Boulevard [Islandwide Delivery]
Airview Building
Albert Cen

### Tried using difflib library to standardize the entries up to 80% matching.( Didn't work)

In [10]:
import difflib

# Filter the DataFrame to include only addresses starting with 'a'
addresses_starting_with_a = establishment_df[establishment_df['address'].str.lower().str.startswith('a')]['address'].unique()

# Define a function to find the best match for each address starting with 'a'
def standardize_address(address):
    matches = difflib.get_close_matches(address, addresses_starting_with_a, n=1, cutoff=0.7)
    if matches:
        return matches[0]
    else:
        return address

# Apply the standardization function to addresses starting with 'a'
standardized_addresses_starting_with_a = [standardize_address(address) for address in addresses_starting_with_a]

# Display the original and standardized addresses
print("Original Addresses:")
print(addresses_starting_with_a)

print("\nStandardized Addresses:")
print(standardized_addresses_starting_with_a)


Original Addresses:
['Anson House' 'Alkaff Mansion' 'Academia' 'Alexandra Road' 'Altez'
 'Anson' 'Apex @ Henderson'
 'Ayer Rajah Food Centre [Stall 10] [Islandwide Delivery]'
 'Alexandra Retail Centre' 'Alexandra Retail Centre [Islandwide Delivery]'
 'Asia Square Tower 2 [Islandwide Delivery]' 'Arc [Islandwide Delivery]'
 'Amoy Street Food Centre [Islandwide Delivery]'
 'Ayer Rajah Food Centre [Islandwide Delivery]' 'Ayer Rajah Crescent'
 'Alexandra Village Food Centre' 'Alexandra Central Mall'
 'Alexandra Hawker Centre [Islandwide Delivery]'
 'Anchorpoint Shopping Centre' 'Anchor Point' 'Alexandra Central'
 'Avocado & Natural Foods  (Anchorpoint Shopping Centre)' 'Arc'
 'Ayer Rajah Food Centre 1' 'Alexandra Retail Centre Psa Building'
 'Abc Brickworks Market & Food Centre' 'Ascent' 'Alexandra' 'Anchorpoint'
 'Abc Brickworks Market & Food Centre [Stall 12]'
 'Abc Brickworks Market & Food Centre [Stall 15]'
 'Abc Brickworks Market And Food Centre [Stall 8]'
 'Ayer Rajah Food Centre I' '

### The result shows the total number of entries are the same before and after 'standardization' using the 'difflib' library

In [11]:
# Count the total number of entries before standardization
total_entries_before = len(addresses_starting_with_a)

# Count the total number of entries after standardization
total_entries_after = len(set(standardized_addresses_starting_with_a))

# Print the total number of entries before and after standardization
print("Total entries with addresses starting with 'a' before standardization:", total_entries_before)
print("Total entries with addresses starting with 'a' after standardization:", total_entries_after)

Total entries with addresses starting with 'a' before standardization: 237
Total entries with addresses starting with 'a' after standardization: 237


### Standardize all the entries that have '[xxx]' and replace all the 'And' with '&' for standardization

In [12]:
import re

# Define a function to standardize addresses and count changes
def standardize_address_and_count(address):
    # Initialize counter for changes
    num_changes = 0
    
    # Remove '[Stall xx]' part using regular expression
    standardized_address = re.sub(r'\[.*?\]', '', address)
    
    # Replace 'And' with '&' and remove leading/trailing spaces
    standardized_address = standardized_address.replace('And', '&').strip()
    
    # Replace any occurrence of 'Abc Brickworks' with 'Abc Brickworks Market & Food Centre'
    if 'Abc Brickworks' in standardized_address:
        standardized_address = standardized_address.replace('Abc Brickworks', 'Abc Brickworks Market & Food Centre')
        num_changes += 1
    
    return standardized_address, num_changes

# Apply the standardization function to the 'address' column of the DataFrame
establishment_df['standardized_address'], num_changes = zip(*establishment_df['address'].apply(standardize_address_and_count))

# Print the total count of entries that were changed
print("Total count of entries changed:", sum(num_changes))

# Print the list of entries that were changed
changed_entries = establishment_df[establishment_df['standardized_address'] != establishment_df['address']]
print("\nList of entries that were changed:")
for index, row in changed_entries.iterrows():
    print(row['address'], '->', row['standardized_address'])


Total count of entries changed: 11

List of entries that were changed:
Heytea Vivo City [Islandwide Delivery] -> Heytea Vivo City
Vivocity [Islandwide Delivery] -> Vivocity
Vivocity [Islandwide Delivery] -> Vivocity
Harbourfront Centre [Islandwide Delivery] -> Harbourfront Centre
Resorts World Sentosa [Islandwide Delivery] -> Resorts World Sentosa
W Singapore Sentosa Cove [Islandwide Delivery] -> W Singapore Sentosa Cove
Telok Blangah Rise [Islandwide Delivery] -> Telok Blangah Rise
33 Kampong Bahru Road [Islandwide Delivery] -> 33 Kampong Bahru Road
Lim Teck Kim Road [Islandwide Delivery] -> Lim Teck Kim Road
Tanjong Pagar Complex [Islandwide Delivery] -> Tanjong Pagar Complex
Neil Road [Islandwide Delivery] -> Neil Road
Everton Park[Islandwide Delivery] -> Everton Park
Neil Road [Islandwide Delivery] -> Neil Road
Tras Link [Islandwide Delivery] -> Tras Link
Telok Blangah Drive [Islandwide Delivery] -> Telok Blangah Drive
Yong Siak View [Islandwide Delivery] -> Yong Siak View
Yeshangh

In [13]:
#To find the total distinct value after changing the values in address column to tittle case.
total_distinct_addresses = establishment_df['address'].nunique()

# Display the total number of distinct addresses
print("Total distinct addresses:", total_distinct_addresses)

Total distinct addresses: 4883


In [14]:
# Step 1: Filter the DataFrame
filtered_df = establishment_df[establishment_df['address'].str.lower().str.startswith(('a'))]

# Step 2: Extract distinct values from the filtered DataFrame
distinct_addresses_filtered = filtered_df['address'].unique()

# Step 3: Sort the distinct values alphabetically
distinct_addresses_filtered_sorted = sorted(distinct_addresses_filtered)

# Display the sorted distinct values
print("Distinct addresses starting with 'a':")
for address in distinct_addresses_filtered_sorted:
    print(address)

Distinct addresses starting with 'a':
A' Posh Bizhub
A'Posh Bizhub
Abc Brickworks Food Centre
Abc Brickworks Market & Food Centre
Abc Brickworks Market & Food Centre [Stall 113]
Abc Brickworks Market & Food Centre [Stall 120]
Abc Brickworks Market & Food Centre [Stall 12]
Abc Brickworks Market & Food Centre [Stall 143]
Abc Brickworks Market & Food Centre [Stall 15]
Abc Brickworks Market & Food Centre [Stall 18]
Abc Brickworks Market And Food Centre [Stall 10]
Abc Brickworks Market And Food Centre [Stall 2]
Abc Brickworks Market And Food Centre [Stall 8]
Acacia Breeze @ Yishun
Acacia Court
Academia
Academy Of Singapore Teachers
Ace Community Club
Adam Road Food Centre
Adda
Adelphi Park Estate
Admiralty
Admiralty Link
Admiralty Street
Admiralty [Islandwide Delivery]
Admiralty[Islandwide Delivery]
Admirax
Admirax [Islandwide Delivery]
Agape Village
Ah Hood
Ah Hood Road
Ah Wang Kway Chap
Air View Building
Airport Boulevard
Airport Boulevard [Islandwide Delivery]
Airview Building
Albert Cen

#### 2nd attempt on data standardization (it created a seperate columns instead)

In [15]:
import re

# Define a function to standardize addresses and count changes
def standardize_address_and_count(address):
    # Initialize counter for changes
    num_changes = 0
    
    # Remove '[Stall xx]' part using regular expression
    standardized_address = re.sub(r'\[.*?\]', '', address)
    
    # Replace 'And' with '&' and remove leading/trailing spaces
    standardized_address = standardized_address.replace('And', '&').strip()
    
    # Replace any occurrence of 'Abc Brickworks' with 'Abc Brickworks Market & Food Centre'
    if 'Abc Brickworks' in standardized_address:
        standardized_address = standardized_address.replace('Abc Brickworks', 'Abc Brickworks Market & Food Centre')
        num_changes += 1
    
    return standardized_address, num_changes

# Apply the standardization function to the 'address' column of the DataFrame
establishment_df['address'], num_changes = zip(*establishment_df['address'].apply(standardize_address_and_count))

# Print the total count of entries that were changed
print("Total count of entries changed:", sum(num_changes))

# Print the list of entries that were changed
changed_entries = establishment_df[establishment_df['standardized_address'] != establishment_df['address']]

print("\nList of entries that were changed:")
for index, row in changed_entries.iterrows():
    print(row['address'], '->', row['standardized_address'])


Total count of entries changed: 11

List of entries that were changed:


In [16]:
# Step 1: Filter the DataFrame
filtered_df = establishment_df[establishment_df['address'].str.lower().str.startswith(('a'))]

# Step 2: Extract distinct values from the filtered DataFrame
distinct_addresses_filtered = filtered_df['address'].unique()

# Step 3: Sort the distinct values alphabetically
distinct_addresses_filtered_sorted = sorted(distinct_addresses_filtered)

# Display the sorted distinct values
print("Distinct addresses starting with 'a':")
for address in distinct_addresses_filtered_sorted:
    print(address)

Distinct addresses starting with 'a':
A' Posh Bizhub
A'Posh Bizhub
Abc Brickworks Market & Food Centre Food Centre
Abc Brickworks Market & Food Centre Market & Food Centre
Acacia Breeze @ Yishun
Acacia Court
Academia
Academy Of Singapore Teachers
Ace Community Club
Adam Road Food Centre
Adda
Adelphi Park Estate
Admiralty
Admiralty Link
Admiralty Street
Admirax
Agape Village
Ah Hood
Ah Hood Road
Ah Wang Kway Chap
Air View Building
Airport Boulevard
Airview Building
Albert Centre
Alexandra
Alexandra Central
Alexandra Central Mall
Alexandra Hawker Centre
Alexandra Hospital
Alexandra Retail Centre
Alexandra Retail Centre Psa Building
Alexandra Road
Alexandra Technopark
Alexandra Village Food Centre
Aljunied
Aljunied 119 Food House
Aljunied Ave 2
Aljunied Ave 3
Aljunied Ave 4
Aljunied Ave 5
Aljunied Avenue 2
Aljunied B
Aljunied Crescent
Aljunied Industrial Complex
Aljunied Industrial Estate
Aljunied Mrt
Aljunied Mrt Station
Aljunied Road
Alkaff Crescent
Alkaff Mansion
Alkaff Vista
Alocassia

### The distinct Values reduced from 4883 to 4029

In [17]:
#To find the total distinct value after standardizing the data with removal of '[xxx]' and change 'And' to '&'
total_distinct_addresses = establishment_df['address'].nunique()

# Display the total number of distinct addresses
print("Total distinct addresses:", total_distinct_addresses)

Total distinct addresses: 4029


### Further standiardize the entries in address column by removing whatever additional information after the add like brackets and such, replace all the 'Amk' to 'Ang Mo Kio'

In [18]:
import re

# Define a function to standardize addresses
def standardize_address(address):
    # Condition 1: Remove additional information after the address
    address = re.sub(r'\s*\([^)]*\)', '', address)

    # Condition 2: Replace variations of 'Ayer Rajah Food Centre' with 'Ayer Rajah Food Centre'
    if 'Ayer Rajah Food Centre' in address:
        address = 'Ayer Rajah Food Centre'

    # Condition 3: Replace variations of 'Ayer Rajah CC' with 'Ayer Rajah CC'
    elif 'Ayer Rajah Cc' in address or 'Ayer Rajah Community Centre' in address:
        address = 'Ayer Rajah CC'

    # Condition 4: Replace variations of 'Asia Square' with 'Asia Square'
    elif 'Asia Square' in address:
        address = 'Asia Square'

    # Replace variation 'Abc Brickworks Market & Food Centre Market & Food Centre Food Centre' 
    elif 'Abc Brickworks Market & Food Centre' in address:
        address = 'Abc Brickworks Market & Food Centre'

        
    # Condition 5: Replace 'Amk' with 'Ang Mo Kio'
    address = address.replace('Amk', 'Ang Mo Kio')

    #Replace variation 'Abc Brickworks Market & Food Centre Market & Food Centre Food Centre' 
    
    return address

# Apply the standardization function to the 'address' column of the DataFrame
establishment_df['address'] = establishment_df['address'].apply(standardize_address)


In [19]:
# Step 1: Filter the DataFrame
filtered_df = establishment_df[establishment_df['address'].str.lower().str.startswith(('a'))]

# Step 2: Extract distinct values from the filtered DataFrame
distinct_addresses_filtered = filtered_df['address'].unique()

# Step 3: Sort the distinct values alphabetically
distinct_addresses_filtered_sorted = sorted(distinct_addresses_filtered)

# Display the sorted distinct values
print("Distinct addresses starting with 'a':")
for address in distinct_addresses_filtered_sorted:
    print(address)

Distinct addresses starting with 'a':
A' Posh Bizhub
A'Posh Bizhub
Abc Brickworks Market & Food Centre
Acacia Breeze @ Yishun
Acacia Court
Academia
Academy Of Singapore Teachers
Ace Community Club
Adam Road Food Centre
Adda
Adelphi Park Estate
Admiralty
Admiralty Link
Admiralty Street
Admirax
Agape Village
Ah Hood
Ah Hood Road
Ah Wang Kway Chap
Air View Building
Airport Boulevard
Airview Building
Albert Centre
Alexandra
Alexandra Central
Alexandra Central Mall
Alexandra Hawker Centre
Alexandra Hospital
Alexandra Retail Centre
Alexandra Retail Centre Psa Building
Alexandra Road
Alexandra Technopark
Alexandra Village Food Centre
Aljunied
Aljunied 119 Food House
Aljunied Ave 2
Aljunied Ave 3
Aljunied Ave 4
Aljunied Ave 5
Aljunied Avenue 2
Aljunied B
Aljunied Crescent
Aljunied Industrial Complex
Aljunied Industrial Estate
Aljunied Mrt
Aljunied Mrt Station
Aljunied Road
Alkaff Crescent
Alkaff Mansion
Alkaff Vista
Alocassia
Alocassia Apartments
Alpha Industrial Building
Altez
American Grill


#### The distint values reduced further from original 4883 to 3971

In [20]:
#To find the total distinct value after standardizing the data with removal of '[xxx]' and change 'And' to '&'
total_distinct_addresses = establishment_df['address'].nunique()

# Display the total number of distinct addresses
print("Total distinct addresses:", total_distinct_addresses)

Total distinct addresses: 3971


### This is the standardization suggestion upon further investigation as its only done base on alphabet 'a', in future more cleaning needed to standardize the address to have better grouping

In [21]:
print(establishment_df.isnull().sum())

id_source                  0
name                       6
address                    0
country                    0
cuisine                    2
currency                  19
delivery_cost             51
lat                        0
lon                        0
opening_hours              0
image_url                 11
radius                     0
rating                  2132
reviews_nr              2534
delivery_options           0
promo                   7359
loc_type                   0
delivery_by                0
delivery_time            183
standardized_address       0
dtype: int64


#### Filter out corrupt Data . Removing rows with Null values in 'name' column 
- Possible reasons as the name shows test this might be test vendors at the initial grab phrase so dropping this rows

In [22]:
# Drop rows with null values in the 'name' column
establishment_df.dropna(subset=['name'],inplace=True)

In [23]:
print(establishment_df.isnull().sum())

id_source                  0
name                       0
address                    0
country                    0
cuisine                    2
currency                  19
delivery_cost             51
lat                        0
lon                        0
opening_hours              0
image_url                 11
radius                     0
rating                  2126
reviews_nr              2528
delivery_options           0
promo                   7354
loc_type                   0
delivery_by                0
delivery_time            183
standardized_address       0
dtype: int64


In [24]:
establishment_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16130 entries, 0 to 16135
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   id_source             16130 non-null  object 
 1   name                  16130 non-null  object 
 2   address               16130 non-null  object 
 3   country               16130 non-null  object 
 4   cuisine               16128 non-null  object 
 5   currency              16111 non-null  object 
 6   delivery_cost         16079 non-null  float64
 7   lat                   16130 non-null  float64
 8   lon                   16130 non-null  float64
 9   opening_hours         16130 non-null  object 
 10  image_url             16119 non-null  object 
 11  radius                16130 non-null  int64  
 12  rating                14004 non-null  float64
 13  reviews_nr            13602 non-null  float64
 14  delivery_options      16130 non-null  object 
 15  promo                 87

In [25]:
# Filter the DataFrame to select rows with null values in the 'rating' column
establishment_df[establishment_df['rating'].isnull()].head(5)


id_source                  name         address    country  \
47  4-C2TYVNCKMAEBSA     Pet Lovers Centre        Vivocity  Singapore   
50  4-C2KWT4CGAK3DC2   Barossa Bar & Grill       Vivo City  Singapore   
64  4-C2UBV8MHHADJG6  Tree Side Nasi Lemak       Vivo City  Singapore   
73  4-C2TYTCLHWBVKHE        Ola Beach Club  Ola Beach Club  Singapore   
84  4-C2MTBB4FE6NVFE            Thai Ai Ai       Vivo City  Singapore   

                                              cuisine currency  delivery_cost  \
47  ["Mart", "Pet Accessories", "Pet Care", "Pet F...      SGD          570.0   
50                                        ["Western"]      SGD          570.0   
64                             ["Asian", "Malaysian"]      SGD          570.0   
73                           ["Beverages", "Western"]      SGD          760.0   
84                         ["Asian", "Local", "Thai"]      SGD          570.0   

         lat         lon                                      opening_hours  \
47  1.265074  103.822735  {"open": true, "displayedHours": "10:00-21:40"...   
50  1.265002  103.822709  {"open": true, "displayedHours": "11:30-21:00"...   
64  1.264305  103.822309  {"open": true, "displayedHours": "10:30-21:00"...   
73  1.251185  103.817939  {"open": true, "displayedHours": "10:00-19:30"...   
84  1.264305  103.822309  {"open": true, "displayedHours": "09:00-21:45"...   

                                            image_url  radius  rating  \
47  https://d1sag4ddilekf6.cloudfront.net/compress...    2500     NaN   
50  https://d1sag4ddilekf6.cloudfront.net/compress...    5000     NaN   
64  https://d1sag4ddilekf6.cloudfront.net/compress...    5000     NaN   
73  https://d1sag4ddilekf6.cloudfront.net/compress...    2500     NaN   
84  https://d1sag4ddilekf6.cloudfront.net/compress...    5000     NaN   

    reviews_nr   delivery_options                              promo loc_type  \
47         NaN      ONLY_DELIVERY  June Specials - Discounted Items!     MART   
50         NaN  DELIVERY_TAKEAWAY                                NaN     FOOD   
64         NaN      ONLY_DELIVERY                                NaN     FOOD   
73         NaN  DELIVERY_TAKEAWAY                                NaN     FOOD   
84         NaN  DELIVERY_TAKEAWAY    30% off with S$15.00 min. order     FOOD   

   delivery_by  delivery_time standardized_address  
47        GRAB           38.0             Vivocity  
50        GRAB           44.0            Vivo City  
64        GRAB           31.0            Vivo City  
73        GRAB           40.0       Ola Beach Club  
84        GRAB           39.0            Vivo City

In [26]:
# Step 2: Extract distinct values from the filtered DataFrame
establishment_df['loc_type'].unique()

array(['FOOD', 'MART'], dtype=object)

#### Drop columns to remove duplicate columns
- ignore the error as it was run twice

In [27]:
# List of columns to drop
columns_to_drop = ['country', 'cuisine', 'currency', 'delivery_cost', 'opening_hours', 'image_url', 'radius', 'delivery_options', 'promo', 'delivery_by', 'delivery_time']

# Drop the specified columns from the DataFrame
establishment_df.drop(columns=columns_to_drop, inplace=True)


In [28]:
establishment_df.tail(5)

id_source                         name  \
16131  4-CZNFTYKKVA3UN2                 Minjiangkueh   
16132         SGDD01192  The Modern Izakaya by Tatsu   
16133         SGDD00961               Raj Restaurant   
16134  4-C2AHJVATN7C2RE   Albismi Indian Muslim Food   
16135  4-C2DXFEK2R6KJTJ  Zam Zam Indian Special Food   

                        address       lat         lon  rating  reviews_nr  \
16131          Ang Mo Kio Ave 3  1.370340  103.843225     5.0         2.0   
16132                       18)  1.295404  103.851698     NaN         NaN   
16133             Soho @ Farrer  1.310830  103.852873     3.9        72.0   
16134            Woodlands Road  1.396885  103.753440     3.6        19.0   
16135  Yishun Industrial Park A  1.441651  103.831330     4.3        37.0   

      loc_type      standardized_address  
16131     FOOD          Ang Mo Kio Ave 3  
16132     FOOD                       18)  
16133     FOOD             Soho @ Farrer  
16134     FOOD            Woodlands Road  
16135     FOOD  Yishun Industrial Park A

#### Noted there  was 2 columns for address: 'address' & 'standardized_address' 
- 'standardized_address' column was created as a result of trial and error in the process of data standardization
-  find the distict values of the both columns to chk if the standardization applied correctly to 'address' column

In [29]:
#To find the total distinct value after standardizing the data with removal of '[xxx]' and change 'And' to '&'
total_distinct_addresses = establishment_df['standardized_address' ].nunique()

# Display the total number of distinct addresses
print("Total distinct addresses:", total_distinct_addresses)

Total distinct addresses: 4025


In [30]:
#To find the total distinct value after standardizing the data with removal of '[xxx]' and change 'And' to '&'
total_distinct_addresses = establishment_df['address'].nunique()

# Display the total number of distinct addresses
print("Total distinct addresses:", total_distinct_addresses)

Total distinct addresses: 3967


#### Drop another column that was created as a result of trial and error in the process of data standardization

In [31]:
# List of columns to drop
columns_to_drop = ['standardized_address']

# Drop the specified columns from the DataFrame
establishment_df.drop(columns=columns_to_drop, inplace=True)


In [32]:
establishment_df.head(3)

id_source           name    address       lat         lon  rating  \
0         SGDD01085  Texas Chicken   Vivocity  1.264792  103.822103     3.8   
1  4-CYTDLPUJEP53N6         Subway   Vivocity  1.264741  103.822072     4.2   
2         SGDD05605       LiHO Tea  Vivo City  1.264309  103.821369     4.5   

   reviews_nr loc_type  
0      1591.0     FOOD  
1       197.0     FOOD  
2       353.0     FOOD

#### Change all entries under 'address' column to lowercase to standardized further for easier analytics process in the future

In [33]:
# Convert the values in the 'address' column to lowercase
establishment_df['address'] = establishment_df['address'].str.lower()


In [34]:
establishment_df.head(3)

id_source           name    address       lat         lon  rating  \
0         SGDD01085  Texas Chicken   vivocity  1.264792  103.822103     3.8   
1  4-CYTDLPUJEP53N6         Subway   vivocity  1.264741  103.822072     4.2   
2         SGDD05605       LiHO Tea  vivo city  1.264309  103.821369     4.5   

   reviews_nr loc_type  
0      1591.0     FOOD  
1       197.0     FOOD  
2       353.0     FOOD

### Download neccesay libraries to Load the  establishment dataframe to postgres database

In [35]:
!pip install sqlalchemy
!pip install psycopg2

### Create connection engine and table to be loaded to Postgres

In [36]:
from sqlalchemy import create_engine
#username='postgres'
#password = '123'
#hostname = 'localhost'
#port = 5432
#database = 'grab_db'

db_url = 'postgresql://postgres:123@localhost:5432/grab_db'

#create a connection to the database
#engine = create_engine('postgresql://postgres:admin@localhost:5432/grab_db')
engine = create_engine(db_url)


# Create a new establishment table
commands = ('''Create TABLE IF NOT EXISTS establishment_tbl(id_source VARCHAR PRIMARY KEY,
                                                name VARCHAR,
                                                address VARCHAR,
                                                lat NUMERIC,
                                                lon NUMERIC,
                                                rating NUMERIC,
                                                reviews_nr NUMERIC,
                                                loc_type VARCHAR
                                                );''')

#Copy the data to the PostgreSQL table
establishment_df.to_sql('establishment_tbl', engine, if_exists='replace',index=False)

OperationalError: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: FATAL:  database "grab_db" does not exist

(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [ ]:
import pandas as pd

establishment_df=pd.read_csv("data/Grab SG Restaurants.csv")

establishment_df.head()


## Exploratory Data Analysis

Simple exploratory Data Analysis to understand the data

In [38]:
establishment_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16130 entries, 0 to 16135
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   id_source   16130 non-null  object 
 1   name        16130 non-null  object 
 2   address     16130 non-null  object 
 3   lat         16130 non-null  float64
 4   lon         16130 non-null  float64
 5   rating      14004 non-null  float64
 6   reviews_nr  13602 non-null  float64
 7   loc_type    16130 non-null  object 
dtypes: float64(4), object(4)
memory usage: 1.1+ MB


So the dataset of 16136 rows of grab restaurants
you can see from the count that there are empty values for each column

In [39]:
establishment_df.describe()

lat           lon        rating    reviews_nr
count  16130.000000  16130.000000  14004.000000  13602.000000
mean       1.338520    103.843507      4.238346    343.591604
std        0.045252      0.062058      0.619217    846.893054
min        1.243978    103.625677     -1.000000      1.000000
25%        1.304851    103.806314      4.000000     16.000000
50%        1.332166    103.846022      4.300000     74.000000
75%        1.362679    103.885674      4.600000    303.000000
max        1.469011    103.997253      5.000000  21113.000000

#### name column
First is the name column as the expected count is 16136 but only 16130 is shown there should be 6 null values.</p> 
As you can see below are 6 stores where the name is null and shows most are test stores, probably that this are stores that was given as trial but did not convert to convert to GRAB stores.

Conclusion to drop this 6 stores

In [40]:

establishment_df[establishment_df['name'].isna()]

Empty DataFrame
Columns: [id_source, name, address, lat, lon, rating, reviews_nr, loc_type]
Index: []

#### Cuisine column null values
HAPPY THAI kitchen in clementi i have researched that it is thai restaurant so in cuisine put as thai
https://www.google.com/search?hl=en-SG&gl=sg&q=431+Clementi+Ave+3,+%2301-296+Happy+Thai+Kitchen,+Singapore+120431&ludocid=9550498111253404072&lsig=AB86z5XMdpT1YVyvduw5eaJZY3L5&hl=en&gl=SG
</p>
RELAX BAR, have to opdate the cuisine with beverages, korean based on their fb page

#### delivery_cost column

For delivey_cost column there are insufficient information on why the delivery cost is non-existent and therefore we will leave it for now

#### delivery_time column

as the delivery time has other relevant columns we cannot dropt this columns as there are insufficient information 

### Creating the cuisine_df dataframe

first we are going to replace the establishment_df['cuisine'] list rows from " into ' quote.
Then we create a column for the eventual primary key called cus_id
then we only have 3 columns in cuisine_df which is cuisine_id , id_source and cuisine

In [ ]:
cuisine_df=establishment_df

#clearing ' due to aprostophe 's from cuisine_df['cuisine'] list
cuisine_df['cuisine']=cuisine_df['cuisine'].str.replace('\'',"")

#clearing " from cuisine_df['cuisine'] list
cuisine_df['cuisine']=cuisine_df['cuisine'].str.replace('"',"")

#clearing [,] from cuisine_df['cuisine'] list
cuisine_df['cuisine']=cuisine_df['cuisine'].str.replace('[',"")
cuisine_df['cuisine']=cuisine_df['cuisine'].str.replace(']',"")

# Add a primary key column
cuisine_df['cuisine_id'] = ['cus_' + str(i + 1) for i in range(len(cuisine_df))]

cuisine_df=cuisine_df[['cuisine_id','id_source','cuisine']]

#making all text in cuisine column to lowercase
cuisine_df.loc[:, 'cuisine']=cuisine_df['cuisine'].str.lower()

cuisine_df

null values found in cuisine, this we will fill it with thai for index 2473 and korean, beveragees for indx 15049

In [ ]:
cuisine_df[cuisine_df['cuisine'].isna()]

In [ ]:
# filling up null values with relevant values
cuisine_df.at[2473, 'cuisine'] = 'thai'
cuisine_df.at[15049, 'cuisine'] = 'beverages, korean'

#check row 2473
#cuisine_df.iloc[[2473,2474]]
cuisine_df.iloc[[15049]]

#check if there are any more nulls in cuisine column
#cuisine_df[cuisine_df['cuisine'].isna()]

#cuisine_df

In [ ]:
# Sort the values within each string alphabetically
cuisine_df['cuisine'] = cuisine_df['cuisine'].apply(lambda x: ', '.join(sorted(x.split(', '))))


cuisine_df

In [ ]:
# Split the 'cuisine' column by comma and expand into separate columns
cuisines_split = cuisine_df['cuisine'].str.split(', ', expand=True)

# Rename the new columns
cuisines_split.columns = [f'cuisine_{i+1}' for i in range(cuisines_split.shape[1])]

# Concatenate the new columns with the original DataFrame and drop the old cuisine column
cuisine_df = pd.concat([cuisine_df.drop(columns=['cuisine']), cuisines_split], axis=1)

cuisine_df


### Checking commonality in the grouping to see if we can clean further

In [ ]:
#check commonlity

# Specify selected columns
selected_columns = ['cuisine_1', 'cuisine_2', 'cuisine_3', 'cuisine_4', 'cuisine_5']
# Apply value_counts function to each column and calculate commonality
commonality = cuisine_df[selected_columns].apply(pd.Series.value_counts, axis=1).fillna(0).sum().astype(int)

print(commonality)

In [ ]:
# further cleaning to change 2 michelin star to 1 michelin star

# Find rows where any of the selected columns contain '2 michelin stars'
rows_to_replace = cuisine_df[selected_columns].apply(lambda x: x.str.contains('2 michelin stars')).any(axis=1)
# Replace '2 michelin stars' with 'michelin star'
cuisine_df.loc[rows_to_replace, selected_columns] = cuisine_df[selected_columns].replace('2 michelin stars', '1 michelin star')

# further cleaning to change 1 michelin star to michelin star
rows_to_replace = cuisine_df[selected_columns].apply(lambda x: x.str.contains('1 michelin star')).any(axis=1)
# Replace '2 michelin stars' with 'michelin star'
cuisine_df.loc[rows_to_replace, selected_columns] = cuisine_df[selected_columns].replace('1 michelin star', 'michelin star')

# further cleaning to change michelin guide to michelin star
rows_to_replace = cuisine_df[selected_columns].apply(lambda x: x.str.contains('michelin guide')).any(axis=1)
# Replace '2 michelin stars' with 'michelin star'
cuisine_df.loc[rows_to_replace, selected_columns] = cuisine_df[selected_columns].replace('michelin guide', 'michelin star')

#further cleanin alcoholic beverages to just alcohol
rows_to_replace = cuisine_df[selected_columns].apply(lambda x: x.str.contains('alcoholic beverages')).any(axis=1)
# Replace 'alcoholic beverages' with 'alcohol'
cuisine_df.loc[rows_to_replace, selected_columns] = cuisine_df[selected_columns].replace('alcoholic beverages', 'alcohol')

#to group and count each unique value of cuisine column
# Apply value_counts function to each column and calculate commonality
commonality = cuisine_df[selected_columns].apply(pd.Series.value_counts, axis=1).fillna(0).sum().astype(int)

# Sort commonality counts from biggest to smallest
commonality_sort_values = commonality.sort_values(ascending=False)

# Sort commonality counts alphabetically
commonality_sort_alpha = commonality.sort_index()

In [ ]:
cuisine_df

In [ ]:
print(commonality_sort_values.tail(10))

### adding to a Database

In [ ]:
!pip install sqlalchemy
!pip install psycopg2

In [ ]:
from sqlalchemy import create_engine
username='postgres'
password = '123'
hostname = 'localhost'
port = 5432
database = 'grab_db'

db_url = f'postgresql://{username}:{password}@{hostname}:{port}/{database}'

#create a connection to the database
#engine = create_engine('postgresql://postgres:admin@localhost:5432/grab_db')
engine = create_engine(db_url)


# Create a new cuisine table
commands = ('''Create TABLE IF NOT EXISTS cuisine_tbl(cuisine_id VARCHAR PRIMARY KEY,
                                                id_source VARCHAR,
                                                streaming_service VARCHAR,
                                                cuisine_1 VARCHAR,
                                                cuisine_2 VARCHAR,
                                                cuisine_3 VARCHAR,
                                                cuisine_4 VARCHAR,
                                                cuisine_5 VARCHAR,
                                                );''')

# Step 9: Copy the data to the PostgreSQL table
cuisine_df.to_sql('cuisine_tbl', engine, if_exists='replace', index=False)

#### testing code to upload to postgresql database in elephant SQL

In [ ]:
# from sqlalchemy import create_engine
# #elephantSQL a postgresql SAS version - 

# # Replace these values with your ElephantSQL credentials and database URL
# username = 'dgvjfhxu'
# password = 'eCegJ_4NVogXXa7FzQujcfViOczo9gbf'
# hostname = 'hansken.db.elephantsql.com'
# database = 'dgvjfhxu'

# # Construct the database URL
# db_url = f'postgresql://{username}:{password}@{hostname}/{database}'

# engine = create_engine(db_url)

# # Replace df with your DataFrame
# cuisine_df.to_sql('cuisine_tbl', engine, if_exists='replace', index=False)


# #successful update but did not try further as the relationship not created


## Analysis: from Database

In [ ]:
import psycopg2

# Database connection parameters
DB_NAME = 'grab_db'
DB_USER = 'postgres'
DB_PASSWORD = '123'
DB_HOST = 'localhost'
DB_PORT = '5432'

# Connect to the PostgreSQL database
conn = psycopg2.connect(
    dbname=DB_NAME,
    user=DB_USER,
    password=DB_PASSWORD,
    host=DB_HOST,
    port=DB_PORT
)

# SQL query to select data from a table
query = "SELECT * FROM cuisine_tbl"

# Execute the query and fetch the results
cursor = conn.cursor()
cursor.execute(query)

# Fetch all rows from the result set
rows = cursor.fetchall()

# Get the column names from the cursor description
columns = [desc[0] for desc in cursor.description]

# Create a Pandas DataFrame from the fetched data
cuisine_table = pd.DataFrame(rows, columns=columns)

# Close the cursor and connection
cursor.close()
conn.close()

# Now you can perform analysis on the DataFrame (df)
print(cuisine_table.head())  # Print the first few rows of the DataFrame


## Top 10 establishment categories

In [44]:
# Specify selected columns
selected_columns = ['cuisine_1', 'cuisine_2', 'cuisine_3', 'cuisine_4', 'cuisine_5']

# Apply value_counts function to each column and calculate commonality
cuisine_category = cuisine_table[selected_columns].apply(pd.Series.value_counts, axis=1).fillna(0).sum().astype(int)

# Sort commonality counts from biggest to smallest
cuisine_category_sort_values = cuisine_category.sort_values(ascending=False)

print(cuisine_category_sort_values.head(10))



NameError: name 'cuisine_table' is not defined

In [43]:
from matplotlib import pyplot as plt
from sqlalchemy import create_engine

username='postgres'
password = '123'
hostname = 'localhost'
port = 5432
database = 'grab_db'

db_url = f'postgresql://{username}:{password}@{hostname}:{port}/{database}'


# Connect to PostgreSQL database using SQLAlchemy
engine = create_engine(db_url)
# Query the data from the table
query = "SELECT cuisine_1, cuisine_2, cuisine_3, cuisine_4, cuisine_5 FROM cuisine_tbl"
cuisine_category = pd.read_sql(query, engine)

# Reshape the DataFrame to have a single column for cuisine
cuisine_columns = ['cuisine_1', 'cuisine_2', 'cuisine_3', 'cuisine_4', 'cuisine_5']
cuisine_category = pd.melt(cuisine_category, value_vars=cuisine_columns, var_name='cuisine')

# Count the occurrences of each cuisine
cuisine_category = cuisine_category['value'].value_counts().head(10)

# Plot a bar chart
plt.figure(figsize=(10, 6))
cuisine_category.plot(kind='bar')
plt.title('Cuisine Distribution')
plt.xlabel('Cuisine')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

OperationalError: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: FATAL:  database "grab_db" does not exist

(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [45]:
import pandas as pd
grab_rest = pd.read_csv("data/Grab SG Restaurants.csv")
grab_rest.head()


id_source             name                     address    country  \
0         SGDD01085    Texas Chicken    Texas Chicken - VivoCity  Singapore   
1  4-CYTDLPUJEP53N6           Subway           Subway - Vivocity  Singapore   
2         SGDD05605         LiHO Tea        LiHO Tea - Vivo City  Singapore   
3         SGDD07548         Wingstop         Wingstop - VivoCity  Singapore   
4  4-CY2ZLZLTT2EDJ2  Le Shrimp Ramen  Le Shrimp Ramen - Vivocity  Singapore   

                                             cuisine currency  delivery_cost  \
0  ["Western", "Fast Food", "Halal", "Chicken", "...      SGD          570.0   
1  ["Healthy", "Sandwiches", "Fast Food", "Halal"...      SGD          570.0   
2  ["Same Prices In-Store", "Beverages", "Local",...      SGD          560.0   
3  ["Halal", "Chicken", "Fast Food", "Burger", "W...      SGD          560.0   
4          ["Japanese", "Ramen", "Noodles", "Asian"]      SGD          570.0   

        lat         lon                                      opening_hours  \
0  1.264792  103.822103  {"open": true, "displayedHours": "10:30-21:30"...   
1  1.264741  103.822072  {"open": true, "displayedHours": "12:00-19:00"...   
2  1.264309  103.821369  {"open": true, "displayedHours": "11:30-20:45"...   
3  1.263527  103.821712  {"open": true, "displayedHours": "11:00-21:00"...   
4  1.264810  103.822554  {"open": true, "displayedHours": "10:30-21:00"...   

                                           image_url  radius  rating  \
0  https://d1sag4ddilekf6.cloudfront.net/compress...    5000     3.8   
1  https://d1sag4ddilekf6.cloudfront.net/compress...    3000     4.2   
2  https://d1sag4ddilekf6.cloudfront.net/compress...    5000     4.5   
3  https://d1sag4ddilekf6.cloudfront.net/compress...    5000     4.4   
4  https://d1sag4ddilekf6.cloudfront.net/compress...    5000     4.6   

   reviews_nr   delivery_options  \
0      1591.0      ONLY_DELIVERY   
1       197.0      ONLY_DELIVERY   
2       353.0  DELIVERY_TAKEAWAY   
3      1391.0      ONLY_DELIVERY   
4       309.0  DELIVERY_TAKEAWAY   

                                               promo loc_type delivery_by  \
0  Use 'TEATIME' for FREE delivery between 3PM to...     FOOD        GRAB   
1  Use 'TEATIME' for FREE delivery between 3PM to...     FOOD        GRAB   
2  Use 'TEATIME' for FREE delivery between 3PM to...     FOOD        GRAB   
3  Use 'TEATIME' for FREE delivery between 3PM to...     FOOD        GRAB   
4  Use 'TEATIME' for FREE delivery between 3PM to...     FOOD        GRAB   

   delivery_time  
0           43.0  
1           42.0  
2           41.0  
3           45.0  
4           44.0

In [47]:
grab_rest.columns

Index(['id_source', 'name', 'address', 'country', 'cuisine', 'currency',
       'delivery_cost', 'lat', 'lon', 'opening_hours', 'image_url', 'radius',
       'rating', 'reviews_nr', 'delivery_options', 'promo', 'loc_type',
       'delivery_by', 'delivery_time'],
      dtype='object')

In [48]:
cuisine_table =grab_rest[['id_source','name', 'cuisine']].drop_duplicates().reset_index(drop=True)

cuisine_table


id_source                         name  \
0             SGDD01085                Texas Chicken   
1      4-CYTDLPUJEP53N6                       Subway   
2             SGDD05605                     LiHO Tea   
3             SGDD07548                     Wingstop   
4      4-CY2ZLZLTT2EDJ2              Le Shrimp Ramen   
...                 ...                          ...   
16131  4-CZNFTYKKVA3UN2                 Minjiangkueh   
16132         SGDD01192  The Modern Izakaya by Tatsu   
16133         SGDD00961               Raj Restaurant   
16134  4-C2AHJVATN7C2RE   Albismi Indian Muslim Food   
16135  4-C2DXFEK2R6KJTJ  Zam Zam Indian Special Food   

                                                 cuisine  
0      ["Western", "Fast Food", "Halal", "Chicken", "...  
1      ["Healthy", "Sandwiches", "Fast Food", "Halal"...  
2      ["Same Prices In-Store", "Beverages", "Local",...  
3      ["Halal", "Chicken", "Fast Food", "Burger", "W...  
4              ["Japanese", "Ramen", "Noodles", "Asian"]  
...                                                  ...  
16131  ["Asian", "Bakery & Cake", "Breakfast & Brunch...  
16132                   ["Japanese", "Noodles", "Grill"]  
16133                ["Indian", "Dessert", "Vegetarian"]  
16134                                         ["Indian"]  
16135                                         ["Indian"]  

[16136 rows x 3 columns]

In [49]:
delivery = grab_rest[['id_source','delivery_cost','radius','delivery_options','promo']].drop_duplicates().reset_index(drop=True)
delivery

id_source  delivery_cost  radius          delivery_options  \
0             SGDD01085          570.0    5000             ONLY_DELIVERY   
1      4-CYTDLPUJEP53N6          570.0    3000             ONLY_DELIVERY   
2             SGDD05605          560.0    5000         DELIVERY_TAKEAWAY   
3             SGDD07548          560.0    5000             ONLY_DELIVERY   
4      4-CY2ZLZLTT2EDJ2          570.0    5000         DELIVERY_TAKEAWAY   
...                 ...            ...     ...                       ...   
16131  4-CZNFTYKKVA3UN2            NaN    5000         DELIVERY_TAKEAWAY   
16132         SGDD01192            NaN    3000         DELIVERY_TAKEAWAY   
16133         SGDD00961          560.0    3000  DELIVERY_TAKEAWAY_DINEIN   
16134  4-C2AHJVATN7C2RE            NaN    5000         DELIVERY_TAKEAWAY   
16135  4-C2DXFEK2R6KJTJ            NaN    5000         DELIVERY_TAKEAWAY   

                                                   promo  
0      Use 'TEATIME' for FREE delivery between 3PM to...  
1      Use 'TEATIME' for FREE delivery between 3PM to...  
2      Use 'TEATIME' for FREE delivery between 3PM to...  
3      Use 'TEATIME' for FREE delivery between 3PM to...  
4      Use 'TEATIME' for FREE delivery between 3PM to...  
...                                                  ...  
16131                                                NaN  
16132                                                NaN  
16133                                                NaN  
16134                                                NaN  
16135  Use 'TEATIME' for FREE delivery between 3PM to...  

[16136 rows x 5 columns]

In [50]:
#Details of delivery_df:(ROSNI)
#id_source,delivery_cost, radius, delivery_options, promo 
delivery = grab_rest[['id_source','delivery_cost','radius','delivery_options','promo']]
delivery
#this is the delivery table with rows containing NaN values under promo column

id_source  delivery_cost  radius          delivery_options  \
0             SGDD01085          570.0    5000             ONLY_DELIVERY   
1      4-CYTDLPUJEP53N6          570.0    3000             ONLY_DELIVERY   
2             SGDD05605          560.0    5000         DELIVERY_TAKEAWAY   
3             SGDD07548          560.0    5000             ONLY_DELIVERY   
4      4-CY2ZLZLTT2EDJ2          570.0    5000         DELIVERY_TAKEAWAY   
...                 ...            ...     ...                       ...   
16131  4-CZNFTYKKVA3UN2            NaN    5000         DELIVERY_TAKEAWAY   
16132         SGDD01192            NaN    3000         DELIVERY_TAKEAWAY   
16133         SGDD00961          560.0    3000  DELIVERY_TAKEAWAY_DINEIN   
16134  4-C2AHJVATN7C2RE            NaN    5000         DELIVERY_TAKEAWAY   
16135  4-C2DXFEK2R6KJTJ            NaN    5000         DELIVERY_TAKEAWAY   

                                                   promo  
0      Use 'TEATIME' for FREE delivery between 3PM to...  
1      Use 'TEATIME' for FREE delivery between 3PM to...  
2      Use 'TEATIME' for FREE delivery between 3PM to...  
3      Use 'TEATIME' for FREE delivery between 3PM to...  
4      Use 'TEATIME' for FREE delivery between 3PM to...  
...                                                  ...  
16131                                                NaN  
16132                                                NaN  
16133                                                NaN  
16134                                                NaN  
16135  Use 'TEATIME' for FREE delivery between 3PM to...  

[16136 rows x 5 columns]

In [51]:
#listing the name of columns in delivery data frame
delivery.columns



Index(['id_source', 'delivery_cost', 'radius', 'delivery_options', 'promo'], dtype='object')

In [52]:
delivery.describe()

delivery_cost        radius
count   16085.000000  16136.000000
mean      984.926640   6871.493183
std       656.544752   6170.013565
min       199.000000    578.000000
25%       450.000000   4999.000000
50%       680.000000   5000.000000
75%      1610.000000   5000.000000
max     14000.000000  25000.000000

In [53]:
#copying all the contents of the table "delivery" and assigning the name "delivery_1" 
delivery_1=delivery.copy()
#to delivery_1 adding extra column named delivery_cost_sds with value =delivery_cost/100
delivery_1['delivery_cost_sds']=delivery['delivery_cost']/100
delivery_1

id_source  delivery_cost  radius          delivery_options  \
0             SGDD01085          570.0    5000             ONLY_DELIVERY   
1      4-CYTDLPUJEP53N6          570.0    3000             ONLY_DELIVERY   
2             SGDD05605          560.0    5000         DELIVERY_TAKEAWAY   
3             SGDD07548          560.0    5000             ONLY_DELIVERY   
4      4-CY2ZLZLTT2EDJ2          570.0    5000         DELIVERY_TAKEAWAY   
...                 ...            ...     ...                       ...   
16131  4-CZNFTYKKVA3UN2            NaN    5000         DELIVERY_TAKEAWAY   
16132         SGDD01192            NaN    3000         DELIVERY_TAKEAWAY   
16133         SGDD00961          560.0    3000  DELIVERY_TAKEAWAY_DINEIN   
16134  4-C2AHJVATN7C2RE            NaN    5000         DELIVERY_TAKEAWAY   
16135  4-C2DXFEK2R6KJTJ            NaN    5000         DELIVERY_TAKEAWAY   

                                                   promo  delivery_cost_sds  
0      Use 'TEATIME' for FREE delivery between 3PM to...                5.7  
1      Use 'TEATIME' for FREE delivery between 3PM to...                5.7  
2      Use 'TEATIME' for FREE delivery between 3PM to...                5.6  
3      Use 'TEATIME' for FREE delivery between 3PM to...                5.6  
4      Use 'TEATIME' for FREE delivery between 3PM to...                5.7  
...                                                  ...                ...  
16131                                                NaN                NaN  
16132                                                NaN                NaN  
16133                                                NaN                5.6  
16134                                                NaN                NaN  
16135  Use 'TEATIME' for FREE delivery between 3PM to...                NaN  

[16136 rows x 6 columns]

In [54]:
#selecting only the required columns to make a new df
delivery_df= delivery_1[['id_source','delivery_cost_sds','radius','delivery_options','promo']]
delivery_df

id_source  delivery_cost_sds  radius          delivery_options  \
0             SGDD01085                5.7    5000             ONLY_DELIVERY   
1      4-CYTDLPUJEP53N6                5.7    3000             ONLY_DELIVERY   
2             SGDD05605                5.6    5000         DELIVERY_TAKEAWAY   
3             SGDD07548                5.6    5000             ONLY_DELIVERY   
4      4-CY2ZLZLTT2EDJ2                5.7    5000         DELIVERY_TAKEAWAY   
...                 ...                ...     ...                       ...   
16131  4-CZNFTYKKVA3UN2                NaN    5000         DELIVERY_TAKEAWAY   
16132         SGDD01192                NaN    3000         DELIVERY_TAKEAWAY   
16133         SGDD00961                5.6    3000  DELIVERY_TAKEAWAY_DINEIN   
16134  4-C2AHJVATN7C2RE                NaN    5000         DELIVERY_TAKEAWAY   
16135  4-C2DXFEK2R6KJTJ                NaN    5000         DELIVERY_TAKEAWAY   

                                                   promo  
0      Use 'TEATIME' for FREE delivery between 3PM to...  
1      Use 'TEATIME' for FREE delivery between 3PM to...  
2      Use 'TEATIME' for FREE delivery between 3PM to...  
3      Use 'TEATIME' for FREE delivery between 3PM to...  
4      Use 'TEATIME' for FREE delivery between 3PM to...  
...                                                  ...  
16131                                                NaN  
16132                                                NaN  
16133                                                NaN  
16134                                                NaN  
16135  Use 'TEATIME' for FREE delivery between 3PM to...  

[16136 rows x 5 columns]

In [55]:
##delivery_promo = delivery_df['promo']
#delivery_promo['promo'].fillna ("No promotion", inplace= True)
# this code didnt work. so trying again
# for thiscode delivery_promo =delivery_df[['promo']]
#error message---C:\Users\Ros\AppData\Local\Temp\ipykernel_31724\4246233546.py:7: SettingWithCopyWarning: 
#A value is trying to be set on a copy of a slice from a DataFrame
#See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

#so i converted the delivery_promo table to df
delivery_promo = pd.DataFrame({'promo': delivery_df['promo']})

delivery_promo['promo'].fillna("No Promotion available", inplace= True)
delivery_promo

promo
0      Use 'TEATIME' for FREE delivery between 3PM to...
1      Use 'TEATIME' for FREE delivery between 3PM to...
2      Use 'TEATIME' for FREE delivery between 3PM to...
3      Use 'TEATIME' for FREE delivery between 3PM to...
4      Use 'TEATIME' for FREE delivery between 3PM to...
...                                                  ...
16131                             No Promotion available
16132                             No Promotion available
16133                             No Promotion available
16134                             No Promotion available
16135  Use 'TEATIME' for FREE delivery between 3PM to...

[16136 rows x 1 columns]

delivery_promo = pd.DataFrame({'promo': delivery_promo['promo']}): This line creates a new df by calling the pd.DataFrame() constructor. It takes a dictionary as an argument, where the keys are the column names and the values are the column data. In this case, the dictionary has a single key-value pair where the key is 'promo' (the name of the column) and the value is delivery_promo['promo']. This extracts the 'promo' column from the existing DataFrame delivery_promo and creates a new DataFrame with a single column named 'promo'.Essentially, this line of code is used to isolate the 'promo' column from the original DataFrame and create a new DataFrame with just that column. This step may be necessary to perform operations specifically on the 'promo' column without affecting the original DataFrame structure

In [56]:

# Using .loc to modify the original DataFrame without triggering the warning
delivery_df.loc[:, 'promo'] = delivery_promo['promo']
delivery_df

id_source  delivery_cost_sds  radius          delivery_options  \
0             SGDD01085                5.7    5000             ONLY_DELIVERY   
1      4-CYTDLPUJEP53N6                5.7    3000             ONLY_DELIVERY   
2             SGDD05605                5.6    5000         DELIVERY_TAKEAWAY   
3             SGDD07548                5.6    5000             ONLY_DELIVERY   
4      4-CY2ZLZLTT2EDJ2                5.7    5000         DELIVERY_TAKEAWAY   
...                 ...                ...     ...                       ...   
16131  4-CZNFTYKKVA3UN2                NaN    5000         DELIVERY_TAKEAWAY   
16132         SGDD01192                NaN    3000         DELIVERY_TAKEAWAY   
16133         SGDD00961                5.6    3000  DELIVERY_TAKEAWAY_DINEIN   
16134  4-C2AHJVATN7C2RE                NaN    5000         DELIVERY_TAKEAWAY   
16135  4-C2DXFEK2R6KJTJ                NaN    5000         DELIVERY_TAKEAWAY   

                                                   promo  
0      Use 'TEATIME' for FREE delivery between 3PM to...  
1      Use 'TEATIME' for FREE delivery between 3PM to...  
2      Use 'TEATIME' for FREE delivery between 3PM to...  
3      Use 'TEATIME' for FREE delivery between 3PM to...  
4      Use 'TEATIME' for FREE delivery between 3PM to...  
...                                                  ...  
16131                             No Promotion available  
16132                             No Promotion available  
16133                             No Promotion available  
16134                             No Promotion available  
16135  Use 'TEATIME' for FREE delivery between 3PM to...  

[16136 rows x 5 columns]

In [57]:
delivery_df.info()
#from this we can understand the delivery_cost_sds column has 16085 non-null values.The remaining 51 ROWS are null or NaN

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16136 entries, 0 to 16135
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   id_source          16136 non-null  object 
 1   delivery_cost_sds  16085 non-null  float64
 2   radius             16136 non-null  int64  
 3   delivery_options   16136 non-null  object 
 4   promo              16136 non-null  object 
dtypes: float64(1), int64(1), object(3)
memory usage: 630.4+ KB


In [58]:
# Using isna() method to create a boolean mask for NaN values
nan_mask = delivery_df.isna().any(axis=1)

# Filter the DataFrame to select rows with NaN values
rows_with_nan = delivery_df[nan_mask]

# Display the rows with NaN values
print(rows_with_nan)

              id_source  delivery_cost_sds  radius   delivery_options  \
623    4-CZDWKEXJV7EYNN                NaN   25000  DELIVERY_TAKEAWAY   
647    4-C2MTV33CJZLUSE                NaN   25000      ONLY_DELIVERY   
893    4-CZKKEBUFAFKGCX                NaN   10000      ONLY_DELIVERY   
993    4-CZKKEBWJAJWCR2                NaN   15000      ONLY_DELIVERY   
1009   4-C2KTCUK1PE22CT                NaN   25000      ONLY_DELIVERY   
1039   4-C2NZNF6YLTL3PE                NaN   10000      ONLY_DELIVERY   
1043   4-C2TVNK62ELN3KE                NaN   25000      ONLY_DELIVERY   
1146   4-CZDWKEXCPB31RT                NaN   25000  DELIVERY_TAKEAWAY   
2165   4-CZC2APLUCNTWN2                NaN    2500  DELIVERY_TAKEAWAY   
2176   4-CZD3RK6TGUKJDE                NaN   25000  DELIVERY_TAKEAWAY   
2232   4-C2T2JRLYLXWXR2                NaN    4000      ONLY_DELIVERY   
3831   4-C2T2J62YNPNBGT                NaN   25000  DELIVERY_TAKEAWAY   
4247   4-CZE1VPUUGGE1JT                NaN   25000 

In [59]:
rows_with_nan

id_source  delivery_cost_sds  radius   delivery_options  \
623    4-CZDWKEXJV7EYNN                NaN   25000  DELIVERY_TAKEAWAY   
647    4-C2MTV33CJZLUSE                NaN   25000      ONLY_DELIVERY   
893    4-CZKKEBUFAFKGCX                NaN   10000      ONLY_DELIVERY   
993    4-CZKKEBWJAJWCR2                NaN   15000      ONLY_DELIVERY   
1009   4-C2KTCUK1PE22CT                NaN   25000      ONLY_DELIVERY   
1039   4-C2NZNF6YLTL3PE                NaN   10000      ONLY_DELIVERY   
1043   4-C2TVNK62ELN3KE                NaN   25000      ONLY_DELIVERY   
1146   4-CZDWKEXCPB31RT                NaN   25000  DELIVERY_TAKEAWAY   
2165   4-CZC2APLUCNTWN2                NaN    2500  DELIVERY_TAKEAWAY   
2176   4-CZD3RK6TGUKJDE                NaN   25000  DELIVERY_TAKEAWAY   
2232   4-C2T2JRLYLXWXR2                NaN    4000      ONLY_DELIVERY   
3831   4-C2T2J62YNPNBGT                NaN   25000  DELIVERY_TAKEAWAY   
4247   4-CZE1VPUUGGE1JT                NaN   25000  DELIVERY_TAKEAWAY   
4284   4-C2L2A2JECA4ETN                NaN   25000      ONLY_DELIVERY   
4374   4-C2LXKF61AF3ANN                NaN   25000      ONLY_DELIVERY   
4394   4-C2L1UANXRFWUPA                NaN   25000      ONLY_DELIVERY   
4412   4-C2JZGJ6WNXDGV6                NaN   25000      ONLY_DELIVERY   
4453   4-C2BYCLLCLLKFRX                NaN   25000      ONLY_DELIVERY   
4515   4-CZC1FBTGCJ33R6                NaN   20000  DELIVERY_TAKEAWAY   
4823   4-C2DTPCNUFALHL6                NaN   25000      ONLY_DELIVERY   
7814   4-CZATPBDFL6KXJ6                NaN   20000  DELIVERY_TAKEAWAY   
8614   4-CZJHE7NWCEDCEE                NaN   25000      ONLY_DELIVERY   
9380   4-CZC2DFVKJJCFGT                NaN   25000  DELIVERY_TAKEAWAY   
9592   4-C2NCDBU1VZAGKA                NaN   25000      ONLY_DELIVERY   
9597   4-CZJ3LTWJLAUYJJ                NaN   25000      ONLY_DELIVERY   
9645   4-C2JYJYCER8NEUE                NaN   25000      ONLY_DELIVERY   
9978   4-C2MZV2NWJ2EJVA                NaN   10000      ONLY_DELIVERY   
10028  4-C2NFRCNZGE6HUE                NaN   25000      ONLY_DELIVERY   
10179  4-C2EVEAXGL3CKT2                NaN   10000      ONLY_DELIVERY   
11273  4-CZDYGFB3EX42AT                NaN   25000  DELIVERY_TAKEAWAY   
14076  4-C2NYAYU1EPTCNJ                NaN   25000      ONLY_DELIVERY   
15767  4-C2UGGBB1AA5TAX                NaN    3000  DELIVERY_TAKEAWAY   
16112  4-C2NULJ6XEELYTJ                NaN    5000  DELIVERY_TAKEAWAY   
16113  4-C2CAFBU3T24BGX                NaN    5000  DELIVERY_TAKEAWAY   
16114  4-CZLXBGDCNRAFPA                NaN   10000      ONLY_DELIVERY   
16116  4-C2UHTUVKJB51R2                NaN    2500      ONLY_DELIVERY   
16118  4-CZNVVUUZJXDCR6                NaN    5000  DELIVERY_TAKEAWAY   
16120  4-C2JWAKCFE7C2TJ                NaN    5000  DELIVERY_TAKEAWAY   
16121  4-C2DKPANTSA51VE                NaN    5000  DELIVERY_TAKEAWAY   
16122  4-C2NULJ6WCCCKLE                NaN    5000  DELIVERY_TAKEAWAY   
16123  4-C2BVAKK1J7U3EX                NaN    5000      ONLY_DELIVERY   
16124  4-C2MUAJN3UEWFJN                NaN   10000      ONLY_DELIVERY   
16125  4-CYMUL4M3T2KGUE                NaN    5000  DELIVERY_TAKEAWAY   
16126  4-CZEFR6AUNNXTLA                NaN    5000  DELIVERY_TAKEAWAY   
16127  4-C2TVG3VEC752L2                NaN    5000  DELIVERY_TAKEAWAY   
16129  4-CYVETVMAR7DVLX                NaN    5000  DELIVERY_TAKEAWAY   
16130  4-C2MHKEVGRYXELT                NaN   10000      ONLY_DELIVERY   
16131  4-CZNFTYKKVA3UN2                NaN    5000  DELIVERY_TAKEAWAY   
16132         SGDD01192                NaN    3000  DELIVERY_TAKEAWAY   
16134  4-C2AHJVATN7C2RE                NaN    5000  DELIVERY_TAKEAWAY   
16135  4-C2DXFEK2R6KJTJ                NaN    5000  DELIVERY_TAKEAWAY   

                                                   promo  
623                               No Promotion available  
647    Enjoy 20% off min. spend $25 with promo code "...  
893    Enjoy 20% off min. spend $25 with

In [60]:
#To check how many columns and rows the contain NaN value.51 columns have NaN values under delivery_cost_sds
rows_with_nan.shape

(51, 5)

In [61]:
delivery_df


id_source  delivery_cost_sds  radius          delivery_options  \
0             SGDD01085                5.7    5000             ONLY_DELIVERY   
1      4-CYTDLPUJEP53N6                5.7    3000             ONLY_DELIVERY   
2             SGDD05605                5.6    5000         DELIVERY_TAKEAWAY   
3             SGDD07548                5.6    5000             ONLY_DELIVERY   
4      4-CY2ZLZLTT2EDJ2                5.7    5000         DELIVERY_TAKEAWAY   
...                 ...                ...     ...                       ...   
16131  4-CZNFTYKKVA3UN2                NaN    5000         DELIVERY_TAKEAWAY   
16132         SGDD01192                NaN    3000         DELIVERY_TAKEAWAY   
16133         SGDD00961                5.6    3000  DELIVERY_TAKEAWAY_DINEIN   
16134  4-C2AHJVATN7C2RE                NaN    5000         DELIVERY_TAKEAWAY   
16135  4-C2DXFEK2R6KJTJ                NaN    5000         DELIVERY_TAKEAWAY   

                                                   promo  
0      Use 'TEATIME' for FREE delivery between 3PM to...  
1      Use 'TEATIME' for FREE delivery between 3PM to...  
2      Use 'TEATIME' for FREE delivery between 3PM to...  
3      Use 'TEATIME' for FREE delivery between 3PM to...  
4      Use 'TEATIME' for FREE delivery between 3PM to...  
...                                                  ...  
16131                             No Promotion available  
16132                             No Promotion available  
16133                             No Promotion available  
16134                             No Promotion available  
16135  Use 'TEATIME' for FREE delivery between 3PM to...  

[16136 rows x 5 columns]

In [62]:
grab_rest_name=grab_rest [['id_source','name']]
grab_rest_name

id_source                         name
0             SGDD01085                Texas Chicken
1      4-CYTDLPUJEP53N6                       Subway
2             SGDD05605                     LiHO Tea
3             SGDD07548                     Wingstop
4      4-CY2ZLZLTT2EDJ2              Le Shrimp Ramen
...                 ...                          ...
16131  4-CZNFTYKKVA3UN2                 Minjiangkueh
16132         SGDD01192  The Modern Izakaya by Tatsu
16133         SGDD00961               Raj Restaurant
16134  4-C2AHJVATN7C2RE   Albismi Indian Muslim Food
16135  4-C2DXFEK2R6KJTJ  Zam Zam Indian Special Food

[16136 rows x 2 columns]

In [63]:
# Using isna() method to create a boolean mask for NaN values
nan_mask_main = grab_rest_name.isna().any(axis=1)

# Filter the DataFrame to select rows with NaN values
names_with_nan = grab_rest_name[nan_mask_main]

# Display the rows with NaN values
print(names_with_nan)

             id_source name
628   4-CZDJJTWFC8BAAN  NaN
631   4-C2T2GYAJBEVFJN  NaN
688   4-CZLVCKMHNYTXNX  NaN
692   4-CZKKR7K2JJ22NT  NaN
702   4-CYNANF42AEVAVA  NaN
1031  4-CZEXEPEWN6KKEN  NaN


In [64]:
# List of values to delete
rows_to_delete = ['4-CZDJJTWFC8BAAN','4-C2T2GYAJBEVFJN','4-CZLVCKMHNYTXNX','4-CZKKR7K2JJ22NT', '4-CYNANF42AEVAVA','4-CZEXEPEWN6KKEN']  

# Filtering the DataFrame to exclude rows with specified values in the 'id_source' column
delivery_df = delivery_df[~delivery_df['id_source'].isin(rows_to_delete)]

# Alternatively, if you want to drop rows directly based on the specified values
# delivery_df = delivery_df.drop(delivery_df[delivery_df['id_source'].isin(values_to_delete)].index)

# Verify the DataFrame after deletion
delivery_df #now after 6 rows got deleted,now we have only 16130 rows and 5 columns

id_source  delivery_cost_sds  radius          delivery_options  \
0             SGDD01085                5.7    5000             ONLY_DELIVERY   
1      4-CYTDLPUJEP53N6                5.7    3000             ONLY_DELIVERY   
2             SGDD05605                5.6    5000         DELIVERY_TAKEAWAY   
3             SGDD07548                5.6    5000             ONLY_DELIVERY   
4      4-CY2ZLZLTT2EDJ2                5.7    5000         DELIVERY_TAKEAWAY   
...                 ...                ...     ...                       ...   
16131  4-CZNFTYKKVA3UN2                NaN    5000         DELIVERY_TAKEAWAY   
16132         SGDD01192                NaN    3000         DELIVERY_TAKEAWAY   
16133         SGDD00961                5.6    3000  DELIVERY_TAKEAWAY_DINEIN   
16134  4-C2AHJVATN7C2RE                NaN    5000         DELIVERY_TAKEAWAY   
16135  4-C2DXFEK2R6KJTJ                NaN    5000         DELIVERY_TAKEAWAY   

                                                   promo  
0      Use 'TEATIME' for FREE delivery between 3PM to...  
1      Use 'TEATIME' for FREE delivery between 3PM to...  
2      Use 'TEATIME' for FREE delivery between 3PM to...  
3      Use 'TEATIME' for FREE delivery between 3PM to...  
4      Use 'TEATIME' for FREE delivery between 3PM to...  
...                                                  ...  
16131                             No Promotion available  
16132                             No Promotion available  
16133                             No Promotion available  
16134                             No Promotion available  
16135  Use 'TEATIME' for FREE delivery between 3PM to...  

[16130 rows x 5 columns]

In [65]:
delivery_df.iloc[650:705] #just checking if the rows are deleted.

id_source  delivery_cost_sds  radius   delivery_options  \
652  4-C2K3RYCDALCXVX               21.1   25000  DELIVERY_TAKEAWAY   
653         SGDD10032               15.5   25000  DELIVERY_TAKEAWAY   
654  4-CZCKL341LYMDBE               17.7   25000  DELIVERY_TAKEAWAY   
655  4-C2BJMCKJSEETLA               23.0   25000  DELIVERY_TAKEAWAY   
656  4-CYMFLRM3VNDGRN               20.2   25000  DELIVERY_TAKEAWAY   
657  4-CY4XKE3TSCBFNT               22.1   25000      ONLY_DELIVERY   
658         SGDD10157               17.3   25000  DELIVERY_TAKEAWAY   
659  4-C2LFVVK1GCBCR6               24.6   25000  DELIVERY_TAKEAWAY   
660         SGDD10141               23.0   25000  DELIVERY_TAKEAWAY   
661  4-CZJET3DFPA2AFE               23.0   25000  DELIVERY_TAKEAWAY   
662         SGDD10719               23.0   25000  DELIVERY_TAKEAWAY   
663  4-CZEUT3UCT6XZV6               23.0   25000      ONLY_DELIVERY   
664  4-CYLJWGMAVATCNN               18.1   25000  DELIVERY_TAKEAWAY   
665         SGDD01793               23.0   25000  DELIVERY_TAKEAWAY   
666         SGDD01561               21.2   25000  DELIVERY_TAKEAWAY   
667         SGDD09806               23.0   25000  DELIVERY_TAKEAWAY   
668  4-CZDTFE6GTY3AVJ               23.7   25000  DELIVERY_TAKEAWAY   
669         SGDD05635               18.6   25000  DELIVERY_TAKEAWAY   
670  4-C2DYCFVFL6XCFA               16.0   10000      ONLY_DELIVERY   
671  4-CZKUPAXKRTX3JE                8.0   25000  DELIVERY_TAKEAWAY   
672  4-C2LXJ8CFTJCAGJ               21.1   25000      ONLY_DELIVERY   
673  4-CZEFT4NETY4GTE               23.0   25000  DELIVERY_TAKEAWAY   
674  4-CYXJTB3DKEMJGN               17.8   25000  DELIVERY_TAKEAWAY   
675  4-CZCTJXEWPBK1TA               17.7   25000      ONLY_DELIVERY   
676  4-CY6XVVMCBA22VT               24.9   25000  DELIVERY_TAKEAWAY   
677  4-CYMUL4NERZE2E6               24.9   25000  DELIVERY_TAKEAWAY   
678         SGDD00905               24.9   25000  DELIVERY_TAKEAWAY   
679         SGDD10292               17.0   10000      ONLY_DELIVERY   
680  4-C2NYAYEGRGAWGE               24.2   25000  DELIVERY_TAKEAWAY   
681         SGDD00721               23.4   25000  DELIVERY_TAKEAWAY   
682  4-CZLBSFBYPGETTN               17.7   10000      ONLY_DELIVERY   
683  4-C2AGVU2XJJN1VJ               17.9   10000      ONLY_DELIVERY   
684         SGDD11783               24.9   25000  DELIVERY_TAKEAWAY   
685         SGDD01452               23.0   25000  DELIVERY_TAKEAWAY   
686         SGDD10358               23.0   25000  DELIVERY_TAKEAWAY   
687  4-C2KFAE6UUE2TJJ               22.1   25000  DELIVERY_TAKEAWAY   
689         SGDD09263               23.3   25000  DELIVERY_TAKEAWAY   
690  4-CYWXBAUYRUBBUE               23.0   25000  DELIVERY_TAKEAWAY   
691  4-CZLAVTKZWAJ2J2               23.0   25000      ONLY_DELIVERY   
693  4-C2A2RJ31TYB2R6               16.1   10000      ONLY_DELIVERY   
694  4-CYU2V2KKVKUDRT               23.0    2500  DELIVERY_TAKEAWAY   
695  4-C2LCG3CHNRNHSE               17.7   10000      ONLY_DELIVERY   
696  4-C2DJC6LBCNTZJE               19.0   10000      ONLY_DELIVERY   
697         SGDD07606               24.9   25000  DELIVERY_TAKEAWAY   
698         SGDD12123               21.2   25000  DELIVERY_TAKEAWAY   
699  4-C2KKJ2LAN2L3GN                3.0   25000      ONLY_DELIVERY   
700  4-C2NUJ4CFAJK2R2                5.0   25000      ONLY_DELIVERY   
701         SGDD06876               22.9   25000  DELIVERY_TAKEAWAY   
703         SGDD11819               24.9   25000  DELIVERY_TAKEAWAY   
704         SGDD02908               24.9   25000  DELIVERY_TAKEAWAY   
705         SGDD07978               23.0   25000  DELIVERY_TAKEAWAY   
706         SGDD10543               24.5   25000  DELIVERY_TAKEAWAY   
707         SGDD10509               18.8   25000  DELIVERY_TAKEAWAY   
708  4-C2KCMA6VLB6WRN               15.0   25000      ONLY_DELIVERY   
709         SGDD10401               24.9   25000  DELIVERY_TAKEAWAY   

                                   

In [66]:
#unique_identifiers
delivery_df ['delivery_options'].unique()


array(['ONLY_DELIVERY', 'DELIVERY_TAKEAWAY', 'DELIVERY_DINEIN',
       'DELIVERY_TAKEAWAY_DINEIN'], dtype=object)

In [67]:
delivery_options_df =delivery_df[['delivery_options']]
delivery_options_df

delivery_options
0                 ONLY_DELIVERY
1                 ONLY_DELIVERY
2             DELIVERY_TAKEAWAY
3                 ONLY_DELIVERY
4             DELIVERY_TAKEAWAY
...                         ...
16131         DELIVERY_TAKEAWAY
16132         DELIVERY_TAKEAWAY
16133  DELIVERY_TAKEAWAY_DINEIN
16134         DELIVERY_TAKEAWAY
16135         DELIVERY_TAKEAWAY

[16130 rows x 1 columns]

In [68]:
# Create new columns with default False values
#delivery_options_df['delivery'] = False
#delivery_options_df['take_away'] = False
#delivery_options_df['dine_in'] = False

# Update values based on conditions
#delivery_options_df.loc[delivery_options_df['delivery_options'].str.contains('delivery', case=False), 'delivery'] = True
#delivery_options_df.loc[delivery_options_df['delivery_options'].str.contains('take', case=False), 'take_away'] = True
#delivery_options_df.loc[delivery_options_df['delivery_options'].str.contains('dine', case=False), 'dine_in'] = True

# Display the modified DataFrame
delivery_options_df

delivery_options
0                 ONLY_DELIVERY
1                 ONLY_DELIVERY
2             DELIVERY_TAKEAWAY
3                 ONLY_DELIVERY
4             DELIVERY_TAKEAWAY
...                         ...
16131         DELIVERY_TAKEAWAY
16132         DELIVERY_TAKEAWAY
16133  DELIVERY_TAKEAWAY_DINEIN
16134         DELIVERY_TAKEAWAY
16135         DELIVERY_TAKEAWAY

[16130 rows x 1 columns]

In [70]:
# Create new columns with default False values
delivery_df['delivery'] = False
delivery_df['take_away'] = False
delivery_df['dine_in'] = False

# Update values based on conditions
delivery_df.loc[delivery_df['delivery_options'].str.contains('delivery', case=False), 'delivery'] = True
#For the 'delivery' column, it checks if the 'delivery_options' column contains the word 'delivery' (case insensitive), and if so, sets the corresponding value in the 'delivery' column to True.
delivery_df.loc[delivery_df['delivery_options'].str.contains('take', case=False), 'take_away'] = True
# For the 'take_away' column, it checks if the 'delivery_options' column contains the word 'take' (case insensitive), and if so, sets the corresponding value in the 'take_away' column to True.
delivery_df.loc[delivery_df['delivery_options'].str.contains('dine', case=False), 'dine_in'] = True

# Display the modified DataFrame
delivery_df

C:\Users\ameen\AppData\Local\Temp\ipykernel_148908\3044766428.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df['delivery'] = False
C:\Users\ameen\AppData\Local\Temp\ipykernel_148908\3044766428.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df['take_away'] = False
C:\Users\ameen\AppData\Local\Temp\ipykernel_148908\3044766428.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

Se

id_source  delivery_cost_sds  radius          delivery_options  \
0             SGDD01085                5.7    5000             ONLY_DELIVERY   
1      4-CYTDLPUJEP53N6                5.7    3000             ONLY_DELIVERY   
2             SGDD05605                5.6    5000         DELIVERY_TAKEAWAY   
3             SGDD07548                5.6    5000             ONLY_DELIVERY   
4      4-CY2ZLZLTT2EDJ2                5.7    5000         DELIVERY_TAKEAWAY   
...                 ...                ...     ...                       ...   
16131  4-CZNFTYKKVA3UN2                NaN    5000         DELIVERY_TAKEAWAY   
16132         SGDD01192                NaN    3000         DELIVERY_TAKEAWAY   
16133         SGDD00961                5.6    3000  DELIVERY_TAKEAWAY_DINEIN   
16134  4-C2AHJVATN7C2RE                NaN    5000         DELIVERY_TAKEAWAY   
16135  4-C2DXFEK2R6KJTJ                NaN    5000         DELIVERY_TAKEAWAY   

                                                   promo  delivery  take_away  \
0      Use 'TEATIME' for FREE delivery between 3PM to...      True      False   
1      Use 'TEATIME' for FREE delivery between 3PM to...      True      False   
2      Use 'TEATIME' for FREE delivery between 3PM to...      True       True   
3      Use 'TEATIME' for FREE delivery between 3PM to...      True      False   
4      Use 'TEATIME' for FREE delivery between 3PM to...      True       True   
...                                                  ...       ...        ...   
16131                             No Promotion available      True       True   
16132                             No Promotion available      True       True   
16133                             No Promotion available      True       True   
16134                             No Promotion available      True       True   
16135  Use 'TEATIME' for FREE delivery between 3PM to...      True       True   

       dine_in  
0        False  
1        False  
2        False  
3        False  
4        False  
...        ...  
16131    False  
16132    False  
16133     True  
16134    False  
16135    False  

[16130 rows x 8 columns]

In [71]:
delivery_df


id_source  delivery_cost_sds  radius          delivery_options  \
0             SGDD01085                5.7    5000             ONLY_DELIVERY   
1      4-CYTDLPUJEP53N6                5.7    3000             ONLY_DELIVERY   
2             SGDD05605                5.6    5000         DELIVERY_TAKEAWAY   
3             SGDD07548                5.6    5000             ONLY_DELIVERY   
4      4-CY2ZLZLTT2EDJ2                5.7    5000         DELIVERY_TAKEAWAY   
...                 ...                ...     ...                       ...   
16131  4-CZNFTYKKVA3UN2                NaN    5000         DELIVERY_TAKEAWAY   
16132         SGDD01192                NaN    3000         DELIVERY_TAKEAWAY   
16133         SGDD00961                5.6    3000  DELIVERY_TAKEAWAY_DINEIN   
16134  4-C2AHJVATN7C2RE                NaN    5000         DELIVERY_TAKEAWAY   
16135  4-C2DXFEK2R6KJTJ                NaN    5000         DELIVERY_TAKEAWAY   

                                                   promo  delivery  take_away  \
0      Use 'TEATIME' for FREE delivery between 3PM to...      True      False   
1      Use 'TEATIME' for FREE delivery between 3PM to...      True      False   
2      Use 'TEATIME' for FREE delivery between 3PM to...      True       True   
3      Use 'TEATIME' for FREE delivery between 3PM to...      True      False   
4      Use 'TEATIME' for FREE delivery between 3PM to...      True       True   
...                                                  ...       ...        ...   
16131                             No Promotion available      True       True   
16132                             No Promotion available      True       True   
16133                             No Promotion available      True       True   
16134                             No Promotion available      True       True   
16135  Use 'TEATIME' for FREE delivery between 3PM to...      True       True   

       dine_in  
0        False  
1        False  
2        False  
3        False  
4        False  
...        ...  
16131    False  
16132    False  
16133     True  
16134    False  
16135    False  

[16130 rows x 8 columns]

In [72]:
#adding new index column ,'delivery_id'.
delivery_df['delivery_id']= 'delv_'+(delivery_df.index+1).astype(str)

delivery_df= delivery_df.set_index ('delivery_id').reset_index()

delivery_df

C:\Users\ameen\AppData\Local\Temp\ipykernel_148908\241047542.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df['delivery_id']= 'delv_'+(delivery_df.index+1).astype(str)


delivery_id         id_source  delivery_cost_sds  radius  \
0          delv_1         SGDD01085                5.7    5000   
1          delv_2  4-CYTDLPUJEP53N6                5.7    3000   
2          delv_3         SGDD05605                5.6    5000   
3          delv_4         SGDD07548                5.6    5000   
4          delv_5  4-CY2ZLZLTT2EDJ2                5.7    5000   
...           ...               ...                ...     ...   
16125  delv_16132  4-CZNFTYKKVA3UN2                NaN    5000   
16126  delv_16133         SGDD01192                NaN    3000   
16127  delv_16134         SGDD00961                5.6    3000   
16128  delv_16135  4-C2AHJVATN7C2RE                NaN    5000   
16129  delv_16136  4-C2DXFEK2R6KJTJ                NaN    5000   

               delivery_options  \
0                 ONLY_DELIVERY   
1                 ONLY_DELIVERY   
2             DELIVERY_TAKEAWAY   
3                 ONLY_DELIVERY   
4             DELIVERY_TAKEAWAY   
...                         ...   
16125         DELIVERY_TAKEAWAY   
16126         DELIVERY_TAKEAWAY   
16127  DELIVERY_TAKEAWAY_DINEIN   
16128         DELIVERY_TAKEAWAY   
16129         DELIVERY_TAKEAWAY   

                                                   promo  delivery  take_away  \
0      Use 'TEATIME' for FREE delivery between 3PM to...      True      False   
1      Use 'TEATIME' for FREE delivery between 3PM to...      True      False   
2      Use 'TEATIME' for FREE delivery between 3PM to...      True       True   
3      Use 'TEATIME' for FREE delivery between 3PM to...      True      False   
4      Use 'TEATIME' for FREE delivery between 3PM to...      True       True   
...                                                  ...       ...        ...   
16125                             No Promotion available      True       True   
16126                             No Promotion available      True       True   
16127                             No Promotion available      True       True   
16128                             No Promotion available      True       True   
16129  Use 'TEATIME' for FREE delivery between 3PM to...      True       True   

       dine_in  
0        False  
1        False  
2        False  
3        False  
4        False  
...        ...  
16125    False  
16126    False  
16127     True  
16128    False  
16129    False  

[16130 rows x 9 columns]

In [73]:
delivery_df.iloc[5850:5862]

delivery_id         id_source  delivery_cost_sds  radius  \
5850   delv_5857  4-CZCZNEKAL3M1EE                5.0    5000   
5851   delv_5858  4-C2B3JTEVGKCEN2                4.0    2500   
5852   delv_5859         SGDD00623                5.5    4993   
5853   delv_5860  4-CZL2ETT2EVE3VJ                5.4    5000   
5854   delv_5861  4-CZD2TXJGR4NHT2                4.2    5000   
5855   delv_5862  4-CZLJATEJCAX2N6                4.2    5000   
5856   delv_5863  4-CZNZCPU2CN2UAJ                6.2    9990   
5857   delv_5864  4-C2BXJGLXNJXJHA                4.0   25000   
5858   delv_5865  4-C2TYT8ECEJWTRA                4.1    4950   
5859   delv_5866  4-C2D3G3CETKLEEJ                4.1    5000   
5860   delv_5867  4-CZLGVNAHAN2DCJ                5.0    4000   
5861   delv_5868  4-CYN1J3KTRKLWAJ                4.1    4993   

       delivery_options                                              promo  \
5850      ONLY_DELIVERY  Enjoy 20% off min. spend $25 with promo code "...   
5851  DELIVERY_TAKEAWAY                             No Promotion available   
5852      ONLY_DELIVERY  Use 'TEATIME' for FREE delivery between 3PM to...   
5853  DELIVERY_TAKEAWAY                             No Promotion available   
5854  DELIVERY_TAKEAWAY  Use 'TEATIME' for FREE delivery between 3PM to...   
5855  DELIVERY_TAKEAWAY  Use 'TEATIME' for FREE delivery between 3PM to...   
5856      ONLY_DELIVERY  Enjoy 20% off min. spend $25 with promo code "...   
5857      ONLY_DELIVERY                             No Promotion available   
5858  DELIVERY_TAKEAWAY                    10% off with S$30.00 min. order   
5859  DELIVERY_TAKEAWAY                             No Promotion available   
5860      ONLY_DELIVERY                                   Discounted Items   
5861  DELIVERY_TAKEAWAY  Use 'TEATIME' for FREE delivery between 3PM to...   

      delivery  take_away  dine_in  
5850      True      False    False  
5851      True       True    False  
5852      True      False    False  
5853      True       True    False  
5854      True       True    False  
5855      True       True    False  
5856      True      False    False  
5857      True      False    False  
5858      True       True    False  
5859      True       True    False  
5860      True      False    False  
5861      True       True    False

In [74]:
delivery_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16130 entries, 0 to 16129
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   delivery_id        16130 non-null  object 
 1   id_source          16130 non-null  object 
 2   delivery_cost_sds  16079 non-null  float64
 3   radius             16130 non-null  int64  
 4   delivery_options   16130 non-null  object 
 5   promo              16130 non-null  object 
 6   delivery           16130 non-null  bool   
 7   take_away          16130 non-null  bool   
 8   dine_in            16130 non-null  bool   
dtypes: bool(3), float64(1), int64(1), object(4)
memory usage: 803.5+ KB


In [75]:
#delivery_df.to_csv(r'C:\Users\Ros\Desktop\JDC\grab project\delivery_data.csv')

In [76]:
pip install pandas sqlalchemy psycopg2


Note: you may need to restart the kernel to use updated packages.


In [78]:

from sqlalchemy import create_engine

# Creating connection to grab_db 
engine = create_engine('postgresql://postgres:123@localhost:5432/grab_db')

# Send dataframe to database as a table
delivery_df.to_sql('delivery', engine, if_exists='replace', index=False)


130

### establishment opening hours dataframe

### Creating grab_df and subsetting opening hours column

In [ ]:
import pandas as pd

# import grab dataset
grab_df = pd.read_csv("data/Grab SG Restaurants.csv")

# subset openinghour df with records being dictionaries
op_hours_dict_df = grab_df[["opening_hours"]]

op_hours_dict_df.head()

#### Cleaning the column of dictionaries

In [ ]:
# replacing " " in the dictionary to ' '
op_hours_dict_df = op_hours_dict_df['opening_hours'].str.replace('"',"'")
op_hours_dict_df = pd.DataFrame(op_hours_dict_df)

# replacing 'true' to 'True'
op_hours_dict_df = op_hours_dict_df['opening_hours'].str.replace('true',"'True'")
op_hours_dict_df = pd.DataFrame(op_hours_dict_df)

print(op_hours_dict_df)
print(type(op_hours_dict_df))

#### Splitting the dictionaries into separate columns in a dataframe

In [ ]:
import ast
from pandas import json_normalize

# Ensure that the column is in a proper list of dictionaries format
op_hours_dict_df['opening_hours'] = op_hours_dict_df['opening_hours'].apply(ast.literal_eval)

# Use json_normalize to convert the dictionaries into separate columns
op_hours_dict_df_expanded = op_hours_dict_df.join(json_normalize(op_hours_dict_df['opening_hours'])).drop('opening_hours', axis=1)

print(op_hours_dict_df_expanded)


#### Joining id_source column from grab_df to op_hours_dict_df_expanded

In [ ]:
# Joining id_source column from grab_df to op_hours_dict_df_expanded
openinghour_df = pd.concat([grab_df[["id_source"]], op_hours_dict_df_expanded], axis=1, sort=False)
                  
print(openinghour_df)

#### Adding index column with prefix

In [ ]:
# Create a new index column and add a prefix
openinghour_df['openinghour_id'] = 'op_' + (openinghour_df.index + 1).astype(str)

# Set new index column to be the first column
openinghour_df = openinghour_df.set_index('openinghour_id').reset_index()

print(openinghour_df)

In [ ]:
import numpy as np

# Count no. of NaN in dataframe
nan_count = openinghour_df.isna().sum().sum()

print(f'Total number of NaN values in the DataFrame: {nan_count}')

In [ ]:
# Number of NaN values for each column
nan_count_per_column_df = openinghour_df.isna().sum()

print(nan_count_per_column_df)

In [ ]:
# No. of establishment minus no. of tempClosed equals 'NaN'
count_open = 16136-12849
print(count_open)

In [ ]:
# Create a new DataFrame based on the condition Open=NaN and tempClosed=True
opennull_tempclosetrue = openinghour_df[pd.isna(openinghour_df['open']) & (openinghour_df['tempClosed'] == 'True')]

print('Total no. of rows of tempClosed establishment = ' + str(len(opennull_tempclosetrue)))

In [ ]:
# Create a new DataFrame based on the condition tempClosed=True
tempclosedtrue = openinghour_df[pd.isna(openinghour_df['tempClosed'])]

print('Total no. of rows of (tempClosed is NaN) establishment = ' + str(len(tempclosedtrue)))

In [ ]:
# Create a new DataFrame based on the condition open=NaN
opentrue = openinghour_df[(openinghour_df['open'] == 'True')]

print('Total no. of rows of (open == "True") establishment = ' + str(len(opentrue)))

### There are 12849 - 7155 = 5694 establishment with  open==NaN and tempClosed==NaN

In [ ]:
12849-7155

In [ ]:
# Create a new DataFrame based on the condition open=NaN and tempClosed=NaN
opennull_tempClosednull = openinghour_df[pd.isna(openinghour_df['open']) & pd.isna(openinghour_df['tempClosed'])]

print('Total no. of rows of (open == "NaN" and tempClosed == "NaN") establishment = ' + str(len(opennull_tempClosednull)))
print(opennull_tempClosednull.head())
print(type(opennull_tempClosednull))

In [ ]:
#Subsetting grab_df with address and id_source
grab_df[["address","id_source"]].head()

In [ ]:
# Performing an inner join on the 'id_source' column to include 'address' column to opennull_tempClosednull
#syntax for .merge >> inner_joined_df = df1.merge(df2, on='key', how='inner')

opennull_tempClosednull_address = grab_df[["address","id_source"]].merge(opennull_tempClosednull, on='id_source', how='inner')
opennull_tempClosednull_address.head()

### Based checking on first 5 establishments at time of interim project, they are currently opened, meaning they were not permanently closed at time of dataset. Therefore, for sake of analysis in our project, it is assumed that all entries with open=NaN and tempClosed=NaN are not closed permanently and therefore included in the analysis of the dataset.

#### Replacing open=NaN to True and tempClosed=NaN to False for rows with open=NaN & tempClosed=NaN

In [ ]:
# Conditionally fill NaN values in open with 'True' and in tempClosed with 'False'
openinghour_df.loc[openinghour_df['open'].isna() & openinghour_df['tempClosed'].isna(), ['open', 'tempClosed']] = [True, False]

#to check filling of NaN values for open=NaN and tempClosed=NaN 
openinghour_df.iloc[351]

#### For open=true and tempClosed=NaN, replace tempClosed=NaN to False
#### For open=NaN and tempClosed=true, replace open=NaN to False
#### For any of the days not = 'Closed', replace open to True and tempClosed to False

In [ ]:
# Conditionally fill NaN values in tempClosed with 'False'
openinghour_df.loc[openinghour_df['tempClosed'].isna(), ['tempClosed']] = ['False']

# Conditionally fill NaN values in open with 'False'
openinghour_df.loc[openinghour_df['open'].isna(), ['open']] = ['False']

# Update 'open' to True and 'tempClosed' to False where any of the days are not = 'Closed'
openinghour_df.loc[(openinghour_df['displayedHours'] != 'closed') 
                     | (openinghour_df['sun'] != 'Closed') 
                     | (openinghour_df['mon'] != 'Closed')
                     | (openinghour_df['tue'] != 'Closed') 
                     | (openinghour_df['wed'] != 'Closed')
                     | (openinghour_df['thu'] != 'Closed') 
                     | (openinghour_df['fri'] != 'Closed')
                     | (openinghour_df['sat'] != 'Closed') 
                     , ['open', 'tempClosed']] = [True, False]

openinghour_df.tail()

#### 9 establishment where displayedHours and all days are = 'Closed'

# should we drop this 9 rows? some are mix n match, some arenot closed on google. MAYBE, they not using grab anymore?

In [ ]:
#displaying rows where displayedHours and all days are = 'Closed'
all_closed = openinghour_df[(openinghour_df['displayedHours'] == 'Closed')
                             & (openinghour_df['sun'] == 'Closed') 
                             & (openinghour_df['mon'] == 'Closed')
                             & (openinghour_df['tue'] == 'Closed') 
                             & (openinghour_df['wed'] == 'Closed')
                             & (openinghour_df['thu'] == 'Closed') 
                             & (openinghour_df['fri'] == 'Closed')
                             & (openinghour_df['sat'] == 'Closed')] 
                     
# Update 'open' to False and 'tempClosed' to True where displayedHours and all days are = 'Closed'
print(len(all_closed))

all_closed_address = grab_df[["address","id_source"]].merge(all_closed, on='id_source', how='inner')
print(all_closed_address)


In [ ]:
pip install psycopg2

In [ ]:
from sqlalchemy import create_engine

# Creating connection to grab_db 
engine = create_engine('postgresql://postgres:123@localhost:5432/grab_db')

# Send dataframe to database as a table
openinghour_df.to_sql('openinghour', engine, if_exists='replace', index=False)

In [ ]:
from sqlalchemy import create_engine

# Creating connection to grab_db in Postgres
engine = create_engine('postgresql://postgres:123@localhost:5432/grab_db')

In [ ]:
# Define SQL script to add foreign keys
foreign_key_script = """
ALTER TABLE establishment_df
ADD FOREIGN KEY (id_source) REFERENCES delivery_df (id_source),
ADD FOREIGN KEY (id_source) REFERENCES openinghour_df (id_source),
ADD FOREIGN KEY (id_source) REFERENCES cuisine_df (id_source);
"""


In [ ]:
from sqlalchemy import text

# Define the SQL script as a string
foreign_key_script = """
ALTER TABLE establishment_tbl
ADD FOREIGN KEY (id_source) REFERENCES delivery (id_source),
ADD FOREIGN KEY (id_source) REFERENCES openinghour (id_source),
ADD FOREIGN KEY (id_source) REFERENCES cuisine_tbl (id_source);
"""

# Create a SQLAlchemy text object from the SQL script
foreign_key_text = text(foreign_key_script)

# Execute SQL script to add foreign keys
with engine.connect() as connection:
    connection.execute(foreign_key_text)



In [ ]:
from sqlalchemy import text

# Query to check table definitions
query = """
SELECT table_name, column_name, constraint_name, constraint_type
FROM information_schema.constraint_column_usage
WHERE table_name = 'establishment_tbl';
"""

# Execute query
with engine.connect() as connection:
    result = connection.execute(text(query))  # Use text() to create a SQLAlchemy text object
    for row in result:
        print(row)

